### ISSUE TITLE
Make Steam web chat remember login forever?

### ISSUE THREAD

**Issue by Jimi-James** [ramboxapp/community-edition#1179]
Steam is currently the only chat service I care about that refuses to stay logged in forever. I have no idea if this is possible for Rambox to fix, since it could easily be because of how cookies work with Steam's web chat. Is it possible? If so, can it be added to a milestone?

If not, maybe some hack can be made to give the Steam tab an unread count when it logs you out? Having to log back in every few days/weeks/months (it's really that inconsistent with when it boots me out) wouldn't be a big deal if I at least knew I was logged out without having to spend who knows how long unknowingly being so before I check the tab.

### ENVIRONMENT

> Rambox: v0.5.12

> OS: Linux

> Arch: x64

**Comment by joe776** [comment]
What I did for XMPP to always log be back in is to add some custom JS that fills the respective input fields and clicks the login button. You would have to search for those in the developer tools and select them by id/name/classname. In my case it looked like this (won't work for Steam!):
`document.getElementsByName("jid")[0].value = "YOUR USERNAME";
 document.getElementsByName("password")[0].value = "YOUR PASSWORD";
 document.getElementsByClassName("pure-button")[0].click();`
Beware that this might get synced when using Auth0!

**Comment by gnidorah** [comment]
Use "Remember me on this computer" checkmark:
![screenshot_20171022_112511](https://user-images.githubusercontent.com/12064730/31859943-c799a9e8-b71b-11e7-8a53-d2c5a69611d8.png)

**Comment by Jimi-James** [comment]
@joe776 That would be incredibly insecure and break whenever the site got redesigned.

@gnidorah I'm already doing that, and it's really not consistently 30 days. Sometimes it's 1 day. Sometimes it's a week. Sometimes it's even more than 30 days. My account already has Steamguard, so I'm not sure if you're saying that I need Steamguard to be remembered or if it could make me stay logged in forever.

**Comment by joe776** [comment]
@Jimi-James Well, it also doesn't make the current state worse. As long as the login page isn't changing it should even get rid of the 30 day timeout.
After all, just my 2 cents. This works for me on multiple services, but it's really only a personal workaround, especially due to login/pw security issues (i'm not using Auth0, so for me it's fine... and I guess the page changes a lot less frequently than every month).

If Steam decides for whatever reason that your session is terminated (IP changed, login from different device, "weird behaviour", ...), there's not much Rambox can do. Detecting the logout and showing a warning sounds like a good general solution. From a very quick Google search, a lot of people seem to have issues with the "remember me" in general.

**Comment by gnidorah** [comment]
@Jimi-James Sorry that I can't help. I though not all know the solution I've provided. Because remember checkmark shows only if you logged in and then logged out (by turning rambox off) into steamguarded account. But it works fine for me, maybe because I turn on Rambox almost every day.

**Comment by Jimi-James** [comment]
I also turn on Rambox every day. I'm still not sure what you mean by "works fine for me." If you're saying you are able to stay logged in for 30 days, then yeah, me too, sometimes. But it sounds like it works even better than that for you?
