### ISSUE TITLE
After boot always ending up with a window completely black.

### ISSUE THREAD

**Issue by SvenMey** [ramboxapp/community-edition#1202]
After pc boot, Rambox start automatically.
But the actual tab are not showing, just a full black canvas/window.

The main-menu is visible, but clicking on View-Reload or View-Reload current service is not solving the problem.

Kind regards

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 x64 6.1.7601

**Comment by maxtros** [comment]
mmnn for me its working...there is a bug when rambox tries to load services when there isn't an internet connection established so you get white screen but always a Reload fix it.

Try to be more specific...what services?...what its you Graphics Card....maybe its drivers related (?)

**Comment by leopanzardo** [comment]
I had the same issue after updating to Rambox version 0.5.13, no menu option fixed it, had to uninstall new version and go back to 0.5.10, that fixed the problem.

I'm running Rambox in the following system:
Dell Inspiron 5555
8GB Ram
1TB HD
Processor: AMD A10-8700P Radeon R6, 10 Compute Cores 4C+6G 1.80 Ghz
Windows 7 64bits
Google Chrome version 61.0.3163.100 (Build oficial) (64 bits) installed

It always worked fine until the 0.5.13 update, and after i downgraded to 0.5.10 kept working fine. The issue was only with version 0.5.13 and there wasn't any drivers change or any system configuration change in between. If you need anything else let me know.

**Comment by leopanzardo** [comment]
By the way, i only have 5 services configured:

Whatsapp
Messenger
Facebook (Custom)
TweetDeck
Trello (Custom)

And they were all working great before the update to 0.5.13, and after the downgrade to 0.5.10 they are still working fine. As i said in my previous post, the issue was only with 0.5.13 version.

**Comment by ryans610** [comment]
I had the same issue for 0.5.13 as well(always black srceen), system as following:
Windows 7 64bits (win32 x64 6.1.7601)
Intel i7-4510U 2.00GHz 4 Cores
NVIDIA GeForce 820M
Google Chrome version 61.0.3163.100 (official) (64bits)

Services used:
Messenger
Steam Chat
Skype
GMail
Telegram

**Comment by Dareiko** [comment]
Same here, one restart with quick click to icon when loading, then black screen won't appear

Specs:
Windows 8.1 x64 build 9600
intel i5-4300U
16GB RAM
Intel HD Graphics 4400

Used services:
WhatsApp x2
Skype x2
Messenger
Telegram

before 5.0.13 was everything ok

**Comment by timm0e** [comment]
Guys, disable Hardware Acceleration, it worked for me. 

Change the config file in %appdata%\Rambox , kill all the Rambox Processes and start it again :)

**Comment by ryans610** [comment]
@timm0e It's working, thank you.

**Comment by liwenjing93** [comment]
Thanks timm0e, screenshot: 
![screenshot_1](https://user-images.githubusercontent.com/9654732/33248650-9d9af13e-d358-11e7-95d8-bd987f42dd29.jpg)

**Comment by allstarleb** [comment]
I fixed it by uninstalling it and reinstalling it. Working now.

**Comment by thoru** [comment]
thanks happend to me too suddenly. disabling gpu in config worked :)
