### ISSUE TITLE
Script to log into mysms automatically

### ISSUE THREAD

**Issue by allstarleb** [ramboxapp/community-edition#1316]
Can anyone assist with the javascript to log into mysms automatically without having to log in again? I would not mind it for the other applications as well like Trello, etc. I am not strong in Javascript so your assistance will be much appreciated. 

I am on windows 7 using rambox latest version.

**Comment by DBX12** [comment]
I use this code snippet to auto-fill my username on various sites. It is inserted as custom code per service. Note that you have to change the `USERNAME_INPUT_SELECTOR` to the correct CSS selector for the username input. This only auto-fills the username, because I do not want to store my password in plain text. However, it should be easy to extend to fill the password too.

```js
const LOGIN_URL = "<URL of site with login form>";
const LOGIN_USERNAME = "<your username>";
// the CSS selector for the username input
const USERNAME_INPUT_SELECTOR = "input.form-control[name='_username']"
$(document).ready(function(){
 if(LOGIN_URL == window.location.href){
  $(USERNAME_INPUT_SELECTOR).val(LOGIN_USERNAME);
 }
});
```
I hope this helps you.

**Comment by allstarleb** [comment]
Thank you

**Comment by Ash258** [comment]
@allstarleb Do you need this script in latest version of rambox (0.5.14)?

**Comment by allstarleb** [comment]
@Ash258 yes please, can you provide it? I also need the script for version 0.5.14

**Comment by Ash258** [comment]
@allstarleb Why not update to latest version (0.5.17)??

**Comment by allstarleb** [comment]
@ash258 yes I am using latest version 0.5.17 
Not sure why I said that I copy pasted the wrong thing. I was supposed to type do you have a script for mysms and teamworkchat as well?

**Comment by Ash258** [comment]
Mysms is working. Using it everyday.
Don't use teamworkchat.
