### ISSUE TITLE
Chats are aligned to top left corner and not filling screen

### ISSUE THREAD

**Issue by anuj-modi** [ramboxapp/community-edition#1317]
### Steps to reproduce
1. Happens every time I open Rambox

Issue has persisted through multiple Rambox and OS updates. I have tried removing the app and redownloading it and that didn't fix it. Zooming in and out with Cmd + "+" and Cmd + "-" just makes it worse.
### Expected behavior

I expect the chat screens to be centered in the window and fill the whole screen
### Actual behavior

It fixates to the top left and leaves a large border in bottom and right of the chat window.
<img width="1249" alt="screen shot 2017-11-22 at 1 10 09 pm" src="https://user-images.githubusercontent.com/12874774/33143036-83fc69cc-cf86-11e7-8607-61ac5510db50.png">

### ENVIRONMENT

> Rambox: v0.5.13

> OS: Mac OS High Sierra 10.13.1

> Arch: x64

**Comment by mythmon** [comment]
I'm getting this as well on Rambox 0.5.14 on Arch Linux. It happens when I change the zoom level of the Rambox tab. If I zoom that tab in, all other apps take up less space on the screen leaving large white borders. If I zoom the Rambox tab out, all the other apps take up more space on the screen. Zooming individual app tabs doesn't affect this. They take up the same amount of space on the screen, and have smaller or bigger text.

**Comment by alxxlc** [comment]
I am getting this issue as well. I hope this gets reopened. I see that issue #815 was closed because it was believed to be just a Slack issue, however, I am getting this issue with all the services I have in Rambox.

It started with Slack (I think this is because I just use it the most) and it kind of slowly spread to my other services. Now, whenever I refresh or add a new service, there is always a white border on the bottom and right sides.

It is possible it has something to do with the Mac's pinch zooming, because it only started on my Slack after I accidentally zoomed in and fixed the zoom. This could just be a coincidence though.

I am using Rambox 0.6.2 from the Homebrew cask repo. This is running on OSX 10.14.1 Mojave.
