### ISSUE TITLE
Services are misaligned inside the Rambox window. (Cant see text box in most services)

### ISSUE THREAD

**Issue by ghost** [ramboxapp/community-edition#1351]
### Steps to reproduce

This happened by accidentally zooming in on MacOS high sierra. I accidentally did the two finger zoom in app, and I can no longer get the chatbox to appear in any of the services.

[Here is an example](https://www.dropbox.com/s/sg0ofpvp61oi9c0/Screenshot%202017-12-07%2016.53.45.png?dl=0)

That is what the bottom of all my slack services look like. I have tried reinstalling the app, removing and re-adding the services, but it always appears like this now. Allo, Inbox, and FB Messenger are also all misaligned.

[the top right corner is also misaligned](https://www.dropbox.com/s/iktitou93d7ovqn/Screenshot%202017-12-07%2016.56.25.png?dl=0)

### ENVIRONMENT

> Version: 0.5.13
> Platform: darwin (x64)
> Electron: 1.7.8
> Chromium: 58.0.3029.110
> Node: 7.9.0
> OS: 10.13.1 High Sierra

**Comment by chris-swu** [comment]
Was able to fix this finally by toggling on and off HIDPI support and restarting between those, then with HIDPI support toggled off I zoomed in/out a couple of times and this was fixed. I am going to leave this open since I still think it would be nice to be able to adjust the window alignment of a service manually.
