### ISSUE TITLE
"Don't disturb" mode prevents sounds from audio and videos on WhatsApp and Facebook Messenger

### ISSUE THREAD

**Issue by joaotorres** [ramboxapp/community-edition#1475]
### Steps to reproduce

1. Turn on "Don't disturb"
2. Play a audio message or video on WhatsApp or Facebook Messenger
3. Hear no sound

### Expected behavior

"Don't disturb" mode should prevent notification and unintended sounds, not sounds coming from audio messages or videos played by the user.

### ENVIRONMENT

Version: 0.5.14
Platform: darwin (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

OS X El Capitan

**Comment by maurice-schleussinger** [comment]
I strongly second this. There is a difference between "Don't disturb" and muting all sounds of an application. If the user deliberately initiates something which plays sounds, they should not be muted!

Don't disturb means: "Don't disturb me with notification (sounds)." 

Some examples of similar systems are: 
* Do not disturb on macOS and iOS. It suppresses (no popup, no sound) all notifications like mail, messages and calls. Can you still listen to Music or play a video? Of course you can.
* Same for Android and Windows as far as I know
* Slack Application: No notifications but you can still play inline content.



I opened an issue https://github.com/saenzramiro/rambox/issues/1751 because I thought it was a bug and now I just release this is the same reason inline Videos (e.g. a Youtube-Video) never played with sound in Rambox…

**Comment by joaotorres** [comment]
The issue still exists and seems to bother many people, should we reopen it?
