### ISSUE TITLE
All newly added translations have Eng strings

### ISSUE THREAD

**Issue by AltS1** [ramboxapp/community-edition#1525]
### Steps to reproduce

1. Launch version 0.5.14 - 0.5.16
2. Change language to any [recently](https://github.com/saenzramiro/rambox/commit/694b5f782be7cd5a61032e9cf9b0b3e05e55058c) added (Ukrainian / [uk.js](https://github.com/saenzramiro/rambox/blob/master/resources/languages/uk.js) for example).
3. After restart language is picked but actual resources are still English

### Expected behavior

Updated translation according to [https://crowdin.com/project/rambox](url)

P.S. As I see they all not approved. What could be done about that?

**Comment by petarov** [comment]
Same thing with [Bulgarian](https://github.com/saenzramiro/rambox/blob/master/resources/languages/bg.js) language strings. Is there a way to update the locale files?

**Comment by caos30** [comment]
I've installed just now last Rambox version (0.6.2) and the problem persist. In my case i want to use catalan translation. I helped to translated it at 100% several months ago... but it doesn't appear NOTHING translated to catalan!! None of the interface labels/titles/buttons/options.

I suspect that there is another problem that not just "translation team issues". Please, can someone of the core team check this issue. 

Thanks in advance. This project can be awesome if this little issues are solved. Cheers.

**Comment by caos30** [comment]
I'm looking now the code of rambox on github project and i see that the location files are on /resources/languages/xx.js, but i cannot download the CSV files with the catalan languages from Crowdin.com (the platform to translate, where the catalan language, and others are already 100% translated). If i could do this download, i can put the translations in the javascript formatted file ca.js to be pulled on github project.

But guys, we need support from you. Even, i suppose that you have an automatic script to do this conversion from Crowdin CSV formatted files to the one JS of Rambox code.

Anyway, please, help the community ;-)

Sincerely, months ago i gave a try to other software similar to Rambox (like Franz) because this reason. It's really a waste of efforts and energy that having people interested in put hours on working on your software you don't answer issues at least... :-(

Cheers.
