### ISSUE TITLE
Window size on startup

### ISSUE THREAD

**Issue by oldenboom** [ramboxapp/community-edition#1553]
On startup RunBox tries to grab as much screen estate as possible. Or in other words, the window size of RunBox is set to about the screen size on startup.

I expect RunBox to remember its previous window size and upon relaunch restore that window size.

	
	-
	> Rambox 0.5.16
	> Electron 1.8.3
	> darwin x64 17.4.0

**Comment by knu** [comment]
I've been seeing the same problem in exactly the same environment.

**Comment by erikw** [comment]
Indeed, rambox should really remember its user-set window size!

Why? Because I like to have it minimized to the tray, only opening up the app when I get a notification. Then I want the app to open on top of all other apps in a small window. Then I dismiss if after replying.

I don't want it to take up the whole screen!

**Comment by erikw** [comment]
@stale Well that was kind of rude of you. Just because developers has not responded does not mean that it's not an issue. Please go an unmark this as stale Mr Stalebot. Thanks!

**Comment by erikw** [comment]
Dear bot, this is not stale.
