### ISSUE TITLE
Implement Music player services in Rambox or via separate app

### ISSUE THREAD

**Issue by MurzNN** [ramboxapp/community-edition#1605]
At now most of people listen music not from local drive, but via different online services like Spotify, Deezer, Google Music, Yandex Music, Youtube, etc. 

All of those services have web interfaces, but they are not comfortable to use in browser tab.

Will be good to implement Music player services type, that can be controlled via Rambox in tabs.

**Comment by MurzNN** [comment]
[Nuvola Apps](https://tiliado.eu/nuvolaplayer/) implement this thing, but will be good to have this functional near the messengers, not as separate app.

**Comment by stanis64** [comment]
You can add custom service to listen music

**Comment by MurzNN** [comment]
Yes, but will be good to have quick controls (play, pause, next, prev, like, dislike, etc) available on hotkeys and tray menu.

**Comment by Trucido** [comment]
> At now most of people listen music not from local drive, but via different online services like Spotify, Deezer, Google Music, Yandex Music, Youtube, etc.
> 
> All of those services have web interfaces, but they are not comfortable to use in browser tab.
> 
> Will be good to implement Music player services type, that can be controlled via Rambox in tabs.

Yes! This would be great to have some kind of special services thing for media/music since some of them need extras like widevine or extra mDNS network functionality, this stuff could be built separately (and with configure/compile flags preferrably since some are nonfree/non-FOSS technically for pure GNU linux distros). This would keep Rambox core slim to allow it to do what it is/was intended for - chat services... also segregating potential malicious or spyware-like behavior from some services from reading others would be a bonus as well. (I'm fairly certain electron shares cache within itself but not entirely sure on the details of it's other process separation and isolation. I potentially see social network sites doing tracking/spying stuff you might not want when you have email or other stuff open in other rambox tabs for example).

There's already a lot of feature requests for music related stuff both here on [rambox](https://github.com/saenzramiro/rambox/) and also on [rambox-services-contrib](https://github.com/saenzramiro/rambox-services-contrib/)
Just to name/reference a few here:

- Support for media keys on keyboard #1199
- Feature-Request: pause iTunes on calls #189 (not even sure if this is still a valid issue...?)
- Spotify in Rambox? #1554
- Google Play Music saenzramiro/rambox-services-contrib#27

...and some others i'm missing here that probably should be tagged/referenced.

**Comment by alien2003** [comment]
try Harmony player

**Comment by Trucido** [comment]
> try Harmony player

Nice find, looks great but multiple electron apps running simultaneously use a lot of resources (ram/cpu etc). To have an all-in-one tabbed web app based thing like rambox support most of our needs would kind of be the point of this and probably why music services are being requested (among other things too).

also @MurzNN - You might want to tag this as a blocker for any music/media related issues/pulls until you're content with the framework (just to organize things better).

**Comment by MurzNN** [comment]
At now I already use Rambox as cloud music player, I pin music tabs to right (Yandex Music, Deezer, MPD web interface). The only missing thing is global buttons (play/pause) and same tray icon menu items for control currently playing music.

**Comment by MurzNN** [comment]
Feature is still needed! Stale bot - go away! =)

**Comment by MurzNN** [comment]
Bump

**Comment by maxerbox** [comment]
Would be great if we implement a better service API.

**Comment by MurzNN** [comment]
I have found good app for control cloud based music: https://gitlab.com/ColinDuquesnoy/MellowPlayer
