### ISSUE TITLE
Remove Local Storage and Cache files from disk after removing Service from Rambox

### ISSUE THREAD

**Issue by MurzNN** [ramboxapp/community-edition#1653]
At now after removing Service from Rambox - it keeps all files on `~/.config/Rambox/Partitions` folder as `slack_12`, `telegram_25` folders (Cache, Cookies, Cookies-journal, Local Storage, Preferences), so after many adds and removes - this folder eats many gigabytes.

Can we remove folders with data after remove service from Rambox? If this files can be still needed, we can ask user to keep them.

**Comment by saenzramiro** [comment]
This is correct. That's why we clear history, clear cache, all stored data, etc. here:
https://github.com/ramboxapp/community-edition/blob/b2e447cd13e8095e90fb0cc68e8c51c6def01b58/app/view/main/MainController.js#L160-L173
But those lines don't remove ALL the data. It will be great if we can find a way to remove it without doing it manually. Maybe this is an Electron bug.

**Comment by saenzramiro** [comment]
Let's continue this in #828.
