### ISSUE TITLE
Cannot use slack

### ISSUE THREAD

**Issue by xinwen5523** [ramboxapp/community-edition#1785]
### Steps to reproduce

1. open the rambox 
2. entry the login ID/PW for slack
3. the page into empty, seems crash. and close the app and open it again, only saw the login page, but still not working as login

### Expected behavior

should be login success

### Actual behavior

 always login failed. 

### ENVIRONMENT

> Rambox: v0.5.17

> OS: MAC 10.13.6

> Arch: x64 or ia32

**Comment by TheGoddessInari** [comment]
I noticed it seems to hang, if you right click the tab and hit reload, it should enter into your slack.

**Comment by spersico** [comment]
sometimes, but i'm doing this since half and hour ago, and it doesn't work

**Comment by saenzramiro** [comment]
Slack changes the way you login or logout and now they execute `window.close()` and that seems to crash/freeze the webview.

If you go to Rambox tab and enable-disable the service every time this happens, will work.

`window.close()` seems to be an Electron bug, because if you open the Developer Console on any website an execute this, will crash.

**Comment by theduke** [comment]
Rambox could overwrite `window.close()` with a no-op function or do something sensible instead.

Hacky but would work.

**Comment by devzsolt** [comment]
Refresh also works. Would be nice to see an automated solution.
