### ISSUE TITLE
So Rambox moves to closed source.. ?

### ISSUE THREAD

**Issue by pschiffe** [ramboxapp/community-edition#1810]
After the release of [Rambox Pro](https://rambox.pro/#pricing), which is [not open source any more](https://github.com/ramboxapp), I'm really interested in the future of this project. [The activity](https://github.com/saenzramiro/rambox/commits/master) for this repo is really low, what makes sense since the focus is probably shifted to the Rambox Pro. There is also zero communication from the developer @saenzramiro to the community regarding the current state and the future plans for this project. Please correct me if I'm wrong, but I couldn't find anything.

And this concerns me - I've been using Rambox for a long time, but the current state of this project is questionable. It seems that this version of the Rambox (open source, in this repo) will be abandoned, where only the closed source version of Rambox Pro will be maintained and developed in the future. I understand that developing of open source project for free is hard, but the combination of open source and paid features / support should be doable.

So, I would like to ask, what's next? What is your opinion, how will you, all users of Rambox, proceed? Will you switch to the Pro version? There is a free option, I think.

I'm also considering switching to [Franz](https://meetfranz.com/). I know Rambox was created as an open source alternative to Franz, but since version 5, it seems that Franz is also [open source](https://github.com/meetfranz/franz). It looks like that Franz has a better security, at least based on quick search for `webSecurity` and `nodeIntegration` attributes. For more info see #1765 , but I'm no expert in this area. On the other hand, Franz is missing RPMs, version 5 is still in beta, with good progress until April, but not so good after that (the latest release is from April), and the communication is as well not that good. @adlk any comments reg. the above?

Thanks all for your input.

**Comment by Mumrau** [comment]
I'm scared that the so-called "free version" is precisely the declination represented by this repository, which gets my really worried too. Indeed the download link on https://rambox.pro/#pricing redirects to https://github.com/saenzramiro/rambox/releases/tag/0.5.17 .

I really hate these monthly subscription which looks like the new trend in the software world, it cause me to leave a lot of apps and projects, and might as well do the same for this one which I loved so much.

**Comment by peterwilli** [comment]
I'm looking for alternatives now: https://www.reddit.com/r/opensource/comments/951g2y/now_that_rambox_has_gone_paid/

**Comment by DidierLmn** [comment]
This repository is licensed under the GPLv3, under this license you have to license derivative works under the same license (as far as I know). Thus this closed source 'Pro version' may be violating the License of this project (assuming it shares the codebase with this repo).

Also, if the pro version still uses the Sencha Ext JS Library it should be licensed under the GPLv3 ([see this issue](https://github.com/saenzramiro/rambox/issues/499)) if no license has been bought.

**Comment by peterwilli** [comment]
@DidierLmn but if it's their own project they are free to change the license right? (Except of the current versions released under GPLv3). Anyway, trying out Franz now. Confirmed open source. They also have a paid subscription model, but it's only for session sync and all, which has nothing to do with hiding features away from free versions.

**Comment by DidierLmn** [comment]
@peterwilli well, I'm no legal expert, but [changing a license appears to be difficult](https://opensource.guide/legal/#what-if-i-want-to-change-the-license-of-my-project). Since there's no contributor agreement which states contributors give away their copyright, they should have an agreement of all contributors to change the license (the way I understand it)

**Comment by MarauderXtreme** [comment]
@peterwilli Franz is "hiding features away" with them not allowing to use self-hosted services like Mattermost or RocketChat if you don't pay.

**Comment by tjorim** [comment]
@DidierLmn Even if a Commercial License was bought for the Sencha Ext JS library, it might still be an issue. The [Sencha Software License Agreement](https://www.sencha.com/legal/sencha-software-license-agreement/) states that "You cannot commence development of an application under GPLv3 license and later convert to a commercial license." by simply purchasing one. Although I don't exactly know if this would apply to derivative works.

**Comment by tjorim** [comment]
@peterwilli They do sync the services and other settings of the app with your account. However, the option to sync sessions (so you don't need to log in to everything again) will be coming to a paid subscription 'soon'.

**Comment by peterwilli** [comment]
@tjorim thanks. I edited the post on Reddit accordingly. I'll change the post here as well.

**Comment by TheGoddessInari** [comment]
Well, it's not as shiny looking as "Rambox Pro", since there was of course zero communication, but I already had a [downstream fork](https://github.com/TheGoddessInari/rambox) going due to the totally insecure practices and lack of activity on the upstream repo here.

Complete open source transparency and no user tracking, as upstream Rambox/Pro has. Happily accepting contributions/help.

**Comment by saenzramiro** [comment]
Guys, I don't pretend to leave this free and open source version. In fact, I'm recruiting active people to maintain this repo alive. If any of you are interested to participate, please contact me via Twitter @rpsaenz. Because of time, I didn't spend to much time for Rambox CE because we were building Rambox Pro. But I will do my best to continue improving Rambox CE.

Of course, there are features that we offer in Pro version that can't be added to CE. But besides that, I pretend to keep it stable.

The reason I'm making the code of Rambox Pro closed, is because I couldn't find a way to prevent the user to bypass the subscription step for "Pro" features. For me, it will be great if I can offer a free version of Rambox Pro, but because the code is open, anyone can bypass to get all features. Am I wrong? Is there a way?

Regarding those critical bugs about security, I will be working on that next days. Also, I have to fix the Auth0 login deprecation problem.

**Comment by TheGoddessInari** [comment]
Features that can't or won't be added to CE? There's a difference.

**Comment by Mumrau** [comment]
Correct me if I'm wrong but given the new look of Rambox Pro it looks like the interface, and thus the codebase has changed a lot.
Which brings maintainability problems, as you can't simply apply patches to both repositories?

**Comment by saenzramiro** [comment]
I opened a thread there explaining this: https://github.com/saenzramiro/rambox/issues/1811

**Comment by john4669** [comment]
I'm very disappointed that after contributing $ early on and sticking with this product waiting for the fabled version "1.0" basic items such as spell check are now only available in a subscription based model.  Subscription based software is nickel and diming everyone to death.  I would have had no problem paying $30-$50 up front and getting free updates until the next major release.  I think that would be fair.  I think I will abandon Rambox for either Wavebox which is slightly less expensive or something else altogether.

**Comment by Tuplad** [comment]
At least fix the logging in issue for Rambox CE. There's a huge bug with auth0 which causes a lot of people to lose their stuff.

**Comment by saenzramiro** [comment]
@Tuplad Yes, we will fix it as I mentioned in https://github.com/ramboxapp/community-edition/issues/1810#issuecomment-410762390 and other important bugs. Also we will add CSS injection and keep improving it.

**Comment by KenMacD** [comment]
@saenzramiro You're aware that the people that would rebuild your app from github to avoid paying will just pull your new one from a torrent? No matter what you add for 'protection' I doubt it'll be more than a day until it's cracked.

I mean, it's your call and all, and I realize you're just looking to make money, it just seems you might be throwing away a loyal community for little gain.

**Comment by ahjolinna** [comment]
I really don't care that there is a (close source) "pro" version as I get that devs need/want money for their work. The only problem I have with the "pro" version is the ridiculous pricing (5$/month or 48$/year) and that you need to use facebook or google to use it. Also the look & feel of the pro version compared to CE version is worse in my opinion...so at least for me I don't see any reason to move from CE to pro

I do get why there is backlash this is nothing new, even [Jolla](https://jolla.com/) gets a lot shit of their [SailfishOS](https://sailfishos.org/) for not being [100% open source](https://sailfishos.org/wiki/Collaborative_Development), and it's because they need to protect their assets to make money (as they are a start-up company).

anyway, I think a better pricing model would at least be better.
for example; free(/open?) basic app with some ads(?) and then a "pro feature" unlock system and no monthly feed. This is something [Fasthub](https://github.com/k0shk0sh/FastHub) (git client for android) is doing.

**Comment by peterwilli** [comment]
@ahjolinna I don't know SailfishOS but I'm pretty ok with their model, after a quick look it seems that applications they've built are closed but the OS itself is open, so it's mainly open-core (correct me if I'm wrong)

In my opinion, Rambox is one of these apps that simply shouldn't be closed. Would you use a closed-source browser where all your private bits go over? I wouldn't.

**Comment by ahjolinna** [comment]
@peterwilli we'll like I said last I would use the FastHub as an example; it's (semi?) open and has pro and enterprise (payment) option for additional features and services.

_Sent from my Xperia X Compact using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
