### ISSUE TITLE
Rambox CE and Rambox Pro

### ISSUE THREAD

**Issue by saenzramiro** [ramboxapp/community-edition#1811]
Hello guys,

As you noticed, today I released the brand new version of Rambox called **Rambox Pro**. I'm very excited and hope you find useful.

### Rambox Community Edition (CE) will keep free and open source!

First, I want to give my sorry for leaving this repo without updates for a few months. This is because we were working hard in Rambox Pro and couldn't spend time answering questions or releasing new updates. I'm recruiting active people to maintain this repo alive. If any of you are interested to participate, please contact me via Twitter @rpsaenz.

We will keep improving Rambox CE and make it more stable, so please help us!

Regards.

**Comment by saenzramiro** [comment]
(save)

**Comment by TheGoddessInari** [comment]
I'd offer to maintain this, since I'm already doing so with a fork, but I'd probably just implement all of your pro features, which would go against your business model.

**Comment by peterwilli** [comment]
@saenzramiro With all the respect to you and the application you built: I love it, and it helped me a lot, I recommended it everywhere.

But building a paid version, which is completely recoded from the CE version, makes less sense to me than just making a paid version based on the free version.

I get that licensing makes this hard, but why not make the free version based on the pro codebase, and then continue to build from there? You mentioned in another thread that you were afraid someone would bypass the subscription model. Well, that's exactly what it is: you pay for a service.

Wouldn't it be nice to offer cloud sync for enterprise customers? This simply cannot be copied, since it would involve copying your network infrastructure (and the closed codebase of the servers). This makes total sense from a developer perspective as well, as all the features from pro will go back into the free version, making it more trustworthy to also contribute to.

I also don't get why you didn't just create a blog post or something explaining what was going on and have the community involved in it. I'm not saying that you should let the community decide over everything, but it makes it less of a surprise.

Anyway, best of luck to you, and I hope that you get what you're hoping for. I still have respect for you and the work that you did, thank you by the way :).

This wasn't a rant, or meant as offence to you :)

**Comment by saenzramiro** [comment]
@peterwilli Thank you for your works.

I decided to build it from scratch because of the technologies I used at that time. The Pro version uses Vue JS instead of Ext JS because Ext JS is GPLv3 and Vue JS MIT.

After thinking for a long time, my idea was to have only one code for both plans (of course for me is the better way for maintenance) but that means I have to close the source code and that's not the initial idea of Rambox.

Because is an app that the code resides in the computer and not loaded from a website (like Slack, Intercom, Evernote, etc) we cannot hide the features in a way that the user at no level can get them without paying. They always can get the code, change the code to a paid version and boom, all features available.

Of course, I'm learning from this because is my first "Paid Product" I launched. So any positive suggestion will appreciate it.

**Comment by saenzramiro** [comment]
Also, considering your suggestion. I started to write a blog about Rambox and I just published my first post.

Please visit: https://medium.com/@Rambox/the-future-of-rambox-ce-and-rambox-pro-3181423dbc86

**Comment by rodneyrod** [comment]
@saenzramiro Probably something to look at is removing the online account stuff from Rambox CE and make that Pro only, simple enough if you revoke the auths to existing clients.
But is there any chance that the CSS changes will make it back to the community edition? That's literally a deal breaker for me, I'd be happy to donate to make that portion FOSS.

**Comment by xenithorb** [comment]
@peterwilli 
>In addition, I think this will make more sense from a business perspective, as I think the costs of maintaining 2 code-bases that are incompatible form one-another outweigh the benefit of providing a premium service on top of a free, complete package.

You seem to be missing the fact that he's being blatant about wanting support for this repo - i.e. it is no longer the focus of this business and he's transitioning away from maintaining it (actually he already did - he admitted to not updating this repo to work on pro in secret).

@rodneyrod 
>@saenzramiro Probably something to look at is removing the online account stuff from Rambox CE and make that Pro only, simple enough if you revoke the auths to existing clients.

I wouldn't get your hopes up - it looks like a lot of effort was put into the new Vue JS app, the re-branding of this repository, and the new website to go along with pro. _[He completely rewrote the app](https://github.com/ramboxapp/community-edition/issues/1811#issuecomment-410797157)_ to get away from copyleft, which is enough for me to stop using this.

**Comment by saenzramiro** [comment]
@rodneyrod Yes, CSS Injection will be in CE.

**Comment by deerhunter91** [comment]
@saenzramiro I am disappointed you went with a subscription for Pro. Like many people I am actively trying to cut down on subscriptions. I was about to take out my credit card and buy Rambox Pro, but I am not paying for a subscription app.

**Comment by keplerk** [comment]
So the CE versión now would be considered a Legacy version ? cuz as you menction you built pro from scratch, but we didnt see any major update in "ce" version from months ago.

**Comment by leoag** [comment]
The irony on this app going pseudo-closed source (basically leaving the CE to die) while I started using it because Franz (the more popular option at the time) hadn't release their source... and now, [Rambox goes to the freezer](https://medium.com/@Rambox/the-future-of-rambox-ce-and-rambox-pro-3181423dbc86) and [Franz](https://meetfranz.com/) has [gone the open source way](https://github.com/meetfranz/franz). It's a shame you couldn't find a way to monetize the application without closing the source code. Good bye Rambox, it was good while it lasted.

**Comment by peterwilli** [comment]
@leoag I had the same thing. People told me to use Franz and I didn't because it was closed, now the tables literally have turned.

I'm still on Rambox CE, I'll wait a bit to see how this all unfolds before migrating all my chats (which is a lot xD)

**Comment by xenithorb** [comment]
The thing about that is, despite Franz going open source, it's not really very useful without a sub too, unless you only use public apps. In rambox I have a ton of custom apps, that were easy to add, while in Fran you have to add a custom recipe off of GitHub to do that, but it's a "developer" feature and also requires a subscription. Franz is just not useful to me because of that. For now, I'm sticking with Rambox-OS and am grateful that someone has stepped up.

**Comment by keplerk** [comment]
Yep, as you say @TheGoddessInari its js, an electron app to be specific, the WHOLE code its stored in the path you install it, not much to do, just check it, drop the main feactures, and vuala, a new open source version of "Rambox Pro"

**Comment by quentinus95** [comment]
@saenzramiro I'm not an expert on that kind of issues, but why did not you get inspiration from GitLab Enterprise (https://gitlab.com/gitlab-org/gitlab-ee/)? Code is still open-source (even if it is not free software) and merged with the open-source part of the project.

I see at least to major issues with the current model:

- "Hiding" the source code is *not* a good way to protect your work. After installing Rambox Pro, it will be a matter of minutes to get the source code
- If i choose to pay, it will help you to work on the paid version, not the open one, which will kill the community edition on a long term basis

I really think this will kill the project. As proposed before, why not opening the source code as it won't protect anything to hide it, and enable a subscription key (including a costly, single buy of the product) to unlock some features? This is basically how Emby works (https://github.com/MediaBrowser/Emby).

You really should do a state of the art of used solutions by other open-source projects with pro/paid versions and choose the most suitable solution for you and your community. I have the feeling that the current one is maybe one of the worst (two versions, no backward compatibility, not the same developer teams, payment which only support paid features, ...).

Thanks for all the work you've put into the project!

**Comment by ontherunvaro** [comment]
To be clear, I need confirmation from @saenzramiro that any contributions to this repo (ramboxapp/community-edition) are not and will not be incorporated into Rambox Pro.

I've just recently contributed to this repo before realizing the info in this thread, and I want to specify that my contributions are under the GPLv3 license and can't be reused for closed source projects.
