### ISSUE TITLE
Backup of settings get stuck

### ISSUE THREAD

**Issue by krambock** [ramboxapp/community-edition#1855]
1) Go to Rambox setup 
2) Click on Backup preferences
3) Get a popup saving.. 

It't get stuck there forever.  I need to reload Rambox to be able to continue working.  (attaching the screen shot) 
![imagen](https://user-images.githubusercontent.com/18543383/45555985-d30a2100-b7ff-11e8-8fc9-93742a11c74f.png)

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> linux x64 3.10.0-862.11.6.el7.x86_64

**Comment by juanjosezg** [comment]
Same here, also when you need to restore a backup from another Rambox instance authentication fails

**Comment by mbesch0711** [comment]
same here. would be important a day.

**Comment by StormPooper** [comment]
Same, even on the updated 0.6.1, Windows 10.

```
Version: 0.6.1
Platform: win32 (x64)
Electron: 2.0.8
Chromium: 61.0.3163.100
Node: 8.9.3
```

**Comment by bud1290** [comment]
Same bug for me.. It's quite anoying .. And after it gets stuck I lose all my login :(

**Comment by leenpaws** [comment]
same here, just created another issue for it, will close newly created issue

**Comment by 5jubs** [comment]
> 
> 
> Same, even on the updated 0.6.1, Windows 10.
> 
> ```
> Version: 0.6.1
> Platform: win32 (x64)
> Electron: 2.0.8
> Chromium: 61.0.3163.100
> Node: 8.9.3
> ```
> 
> _Edit:_ Mentioned below about losing logins. This didn't happen for me after hitting Reload once it was stuck, though it did happen when updating to 0.6.1.

Same happening here :~

**Comment by zetneteork** [comment]
Same issue on `Windows 10` and `Debian - testing` `4.18.0-1-amd64`.
```
Version: 0.6.1
Platform: linux (x64)
Electron: 2.0.8
Chromium: 61.0.3163.100
Node: 8.9.3
```

**Comment by krambock** [comment]
Still happening as others stated, after upgrading.. .and interestingly I found another issue.. 

![imagen](https://user-images.githubusercontent.com/18543383/46697129-8f75bd80-cbd9-11e8-983c-1a6bcd784345.png)

**Comment by mkgo** [comment]
I can confirm the issue is still happening after upgrading to 0.6.1

**Comment by mkgo** [comment]
On my side with the dev tools open the problem seems to be a failed call to : https://rambox.auth0.com/api/v2/users/google-oauth

I tried to setup the env locally to be able to try and debug this issue since this and [https://github.com/ramboxapp/community-edition/issues/1888](1888) is stopping me from being able to setup and use rambox completly now. It will take me a little while since I have to figure out how the auth0 app is setup to be able to use my auth0 account instead. If there is documentation on that part anywhere I would appreciate the link and will try to fix.

**Comment by KReguieg** [comment]
v0.6.1 still have the issue + I don't want to update before backing up...
