### ISSUE TITLE
cannot remove services

### ISSUE THREAD

**Issue by polrus** [ramboxapp/community-edition#1888]
Clicking on the trashbin icon does notthing. Even if I force reload from the menu

	
	-
	> Rambox 0.6.1
	> Electron 2.0.8
	> linux x64 4.12.14-lp150.12.16-default

**Comment by mkgo** [comment]
I've seen an ongoing problem with the remove (trashcan icon) on services. 

It seems to be a hit or miss on removal, will remove some and then will get caught on progress bar roll non-stop. Then a full reload is needed and same thing again, a couple work then same thing happens.

Also I've noticed that after a reload once it got stuck, duplicate services get created. Where it seems if 2 got deleted, 2 duplicates of other services appear after the reload.

Using 0.6.1 .. I've seen this problem since 0.6.0 (even before latest release)

**Comment by SatiricPanda** [comment]
I am also seeing this problem. I recently updated to 0.6.1 from 0.5.8 and had forgotten to manually backup my most recent settings. When I updated, I was able to sign back in, but the backup that synced was from July. 

Now when I try to trash services I no longer need, they get stuck in the progress bar.

Also, when I try to backup my current settings so I don't have to go through this next time, I also get a stuck progress bar for that action saying "Please wait.... Saving backup..." and the bar continuously fills up and starts again at empty.

**Comment by saenzramiro** [comment]
Please upgrade to version 0.6.2 and check if there works ok.

**Comment by polrus** [comment]
still the same
