### ISSUE TITLE
No notification badges for Riot since 0.6.1 (maybe 0.6.0)

### ISSUE THREAD

**Issue by plaperdr** [ramboxapp/community-edition#1892]
Identical to #1882 but with Riot.

### Steps to reproduce

1. Minimize rambox or focus on another window
2. Wait for a message on Riot
3. Wait for the badge on the icon, and it never comes

### Expected behavior

Expected a notification badge on the Riot icon

### Actual behavior

No notifications is shown

### ENVIRONMENT

> Rambox: v0.6.1

> OS: Fedora 28

> Arch: x64

**Comment by kendertas** [comment]
I don't know if this is the same issue I had (no badge icon for Hipchat, only notification), but it seems a wrong injected code.
In service options -> Advanced
I added the same function with the fix

`function updateBadge(e) {
    e >= 1 ? rambox.setUnreadCount(e) : rambox.clearUnreadCount()
}`

in the wrong function, it tried to update "document.title" instead of using the "rambox" object
![gnome-shell-screenshot-2a0oqz](https://user-images.githubusercontent.com/11460938/46807960-7bfa5c00-cd6b-11e8-92c8-56363169126a.png)

**Comment by plaperdr** [comment]
Thanks a lot @kendertas! Your line did the trick for me! The badge shows up properly now!
