### ISSUE TITLE
Rambox tray icon does not match the default Gnome theme. 

### ISSUE THREAD

**Issue by leoheck** [ramboxapp/community-edition#1948]
Rambox tray icon does not match the default Gnome theme. 

Using Ubuntu 18.10
Gnome 3.30
Rambox: **Where I get this from inside the app?** v0.6.2

![image](https://user-images.githubusercontent.com/1277920/47855235-bed7ae80-ddc2-11e8-8550-1706319de1d3.png)

**Comment by maxerbox** [comment]
Well you have to make an icon for it

**Comment by maxerbox** [comment]
Okay, so after some search, I think you are using Suru icon theme.
You will need to fork the [Suru repository](https://github.com/snwh/suru-icon-theme/tree/master), and add a new icon named . You won't be able to push your icon to the Suru git because [they won't accept it](https://github.com/snwh/suru-icon-theme/blob/master/CONTRIBUTING.md). You will have to name this icon "rambox.svg". You can either create a symbolic one or a fullcolor one, well I don't know which icons are taken as a tray icon. You are not forced to follow the build guidelines, you can directly edit your icon folder, located in $XDG_DATA_DIRS/icons. Or, maybe a workaround would be implementing a dark theme detection on Rambox and set the icon directly from the app by editing [this file](https://github.com/ramboxapp/community-edition/blob/4413928fe3729e24724cfd39681c7352156c50ea/electron/tray.js)

**Comment by leoheck** [comment]
Hi, I change themes very often.
But I use Paper icon theme for the icons. 

I agree with you when you said that this should be added by the maintainer of the icon theme. So, based on what you said it means that the Rambox already support the theme icons. I will try to create my icon to see what happens.

**Comment by maxerbox** [comment]
To make it working, since the icon is hardcoded, you will need to install this fix : 
https://github.com/bilelmoussaoui/Hardcode-Tray
It seems that rambox has been added in release v4.3
https://github.com/bilelmoussaoui/Hardcode-Tray/commit/e772fd0efdb41447eb19e1afabf907f69ee5b311

You will need to respect the following names as described [in this file](https://github.com/bilelmoussaoui/Hardcode-Tray/blob/master/data/database/rambox.electron.json) :
rambox-indicator : default icon
rambox-notification : when there is a notification (when the rambox icon is red)

**Comment by maxerbox** [comment]
I think the best thing would be to write a node module to detect current gnome icon theme and provide the icon path, or else the default icon path, instead of installing Hardcode Tray

**Comment by leoheck** [comment]
OH, this is what I am saying, if this is a hardcoded icon, it is a BUG in Rambox that should to be fixed.

**Comment by maxerbox** [comment]
Electron, based on Chromium isn't supporting svgs, so it's a chromium issue.
Hardcode tray is using inkscape to convert svg icons to png
So you need to install hardcode tray.

**Comment by chui2ch** [comment]
> Electron, based on Chromium isn't supporting svgs, so it's a chromium issue.
> Hardcode tray is using inkscape to convert svg icons to png
> So you need to install hardcode tray.

Is this something that is being implemented to Rambox CE? I really like the app, but the Icon is really bothering me. I know its a small gripe, but I want it to match my system.

**Comment by maxerbox** [comment]
Yes, if you are using Papyrus, a theme that supports Hardcode tray (this is what i'm using)
To download hardcode tray : https://github.com/bilelmoussaoui/Hardcode-Tray

**Comment by chui2ch** [comment]
I did that thanks. Will it stay like that, or will I need to run it every time I update rambox?

**Comment by maxerbox** [comment]
Good question,
Since that's a script, you will need to re run it at each update

**Comment by chui2ch** [comment]
So any chance the default rambox icon will be changed? It's not the best looking. I think defaulting to the papyrus, or numix system tray icon would be a much better look.

**Comment by maxerbox** [comment]
Well good question, I think that's up to @saenzramiro. It looks good on Gnome, but idk if the Papyrus icon looks the same on Windows, and if it's copyright free.

**Comment by saenzramiro** [comment]
Sorry for the late response! I really like the idea to have a tray icon to all possible desktop themes.

@maxerbox Do you have an idea how to implement this or a future PR for this?
