### ISSUE TITLE
Allow disabling "No internet connection" popup

### ISSUE THREAD

**Issue by reisi007** [ramboxapp/community-edition#2035]
Hi,

Please refer to this issue: https://github.com/ramboxapp/community-edition/issues/1255

Until the following issue is implemented, can you please make an option, which disables the popup dialogue.

https://github.com/ramboxapp/community-edition/issues/965

Thank you!

**Comment by jerry1970** [comment]
I've called this before but it was closed without someone looking at it so let's try again. #1255 too - closed without a proper solution. C'mon guys... 

### Steps to reproduce
* Install on Linux
* Set rambox to autostart
* Log in, and you will get the error message in question before the OS has had a chance to connect to the wifi.

### Expected behaviour

Rambox opens without stopping its load because of a connection that is not there yet.

### Actual behaviour

Rambox shows a popup that blocks the load of the application. Rambox does not close the popup when the connection has been restored, it just hangs there. Highly annoying.

![rambox-no-connection](https://user-images.githubusercontent.com/5627407/52323095-ff575180-29db-11e9-9a3f-821b5f9bb0de.png)

I hope this is following the issue template and that someone is actually replying to it before the bot closes it. #1255 was from October 2017!

**Comment by reisi007** [comment]
I am against stalebot
