### ISSUE TITLE
[Feature Request] Make unread count accessible out of the app

### ISSUE THREAD

**Issue by Alterrien** [ramboxapp/community-edition#205]
Hello,
It would be nice if there were a way to access unread counts from outside the app, ie. reading it from a textfile. For example, I'm thinking about a Awesome VM widget that could display the number of unread messages. 

Best regards,
Alexandre.

> OS: Archlinux
> 
> Arch: x64

**Comment by Kirogo** [comment]
Hey, thank you !
Awesome WM is a tiling window manager for linux (so windows are automatically resized and reorganised when you create a new one) that you can customize (with lua), and one customizable part is the widgets (The right part of the status bar in the pic attached). It's relatively easy to do, and you can put in pretty much everything you want, so I thought about doing one that would display the number of messages, since I often miss the notifications, and the app is not always on my screen.

Cheers !
Alexandre.
![2016-08-08-183040_3584x1440_scrot](https://cloud.githubusercontent.com/assets/10673033/17487759/83350afc-5d96-11e6-8e74-c30541d9f3b8.png)

**Comment by saenzramiro** [comment]
Got it!

Right now the unread messages is in the title of the Rambox window ("Rambox (6)"). Don't you have a way to read the title of the window?

**Comment by Kirogo** [comment]
It could be possible, but I think it would require some dirty hacks ; isn't it possible to write it to some file on a temp folder ? With maybe details about the number of unread messages for every service ?

**Comment by saenzramiro** [comment]
Of course is possible.

I have to mention that I will do for next versions a more descriptive tooltip for try icon. It will have unread messages for each service.

This solves your problem?

**Comment by orange-buffalo** [comment]
@saenzramiro you've mentioned descriptive tooltip for tray icon. Is there any plan to improve the icon itself to somehow display that there are unread messages (ideally a total number of messages or at least some colorful indicator)?

**Comment by saenzramiro** [comment]
@orange-buffalo Yes, in next version you will see a badge in the taskbar (see #229).

**Comment by orange-buffalo** [comment]
Super, thanks!
