### ISSUE TITLE
Custom Service Unread Badge doesn't work

### ISSUE THREAD

**Issue by burtek** [ramboxapp/community-edition#2087]
### Steps to reproduce

1. Add Feedly as a custom service; log in
2. Use custom JS script:
```js
const originalTitle = document.title;

function checkUnread() {
  const e = document.querySelectorAll('[data-category="global.all"].categoryUnreadCount')[0];
  const count = parseInt(e.innerHTML.trim());

  if(count >= 1) {
    document.title = `(${count}) ${originalTitle}`;
  } else {
    document.title = originalTitle;
  }
}

setInterval(checkUnread, 3000);
```
3. Verify the `document.title` has in fact been changed by typing `document.title` in DevTools console.

### Expected behavior

Unread badge should appear on Feedly tab

### Actual behavior

It does not.
![image](https://user-images.githubusercontent.com/2940958/52308798-96051d80-299e-11e9-85ed-9cab0ee56b44.png)

### ENVIRONMENT

> Version: 0.6.3
> Platform: win32 (x64)
> Electron: 2.0.14
> Chromium: 61.0.3163.100
> Node: 8.9.3

**Comment by Agresina** [comment]
I checked this as it was happening to me.
Try updating the unread count, instead of changing the document title as specified in https://github.com/ramboxapp/community-edition/tree/master/app/model

That is, instead of 

`document.title = '(${count}) ${originalTitle}';`

do

`rambox.setUnreadCount(count);`

(having parsed the count string to number).

In my case I'm also clearing the count, don't know if that is necessary:

`rambox.clearUnreadCount();`

You can try these at the developer tools first.

**Comment by burtek** [comment]
Works perfectly, thanks!

So now my code is:

```js
function checkUnread() {
  const e = document.querySelectorAll('[data-category="global.all"].categoryUnreadCount')[0];
  const count = parseInt(e.innerHTML.trim());

  rambox.setUnreadCount(count || 0);
}

setInterval(checkUnread, 3000);
```

It would be nice to have that in the docs...
