### ISSUE TITLE
Stuck forever when removing disabled services

### ISSUE THREAD

**Issue by yeuking** [ramboxapp/community-edition#2107]
Stuck forever when remove some service.
![20190222-083342](https://user-images.githubusercontent.com/3224525/53211602-bd393b80-367c-11e9-9e79-0043aa40aa47.png)
	
	> Rambox 0.6.3
	> Electron 2.0.14
	> win32 x64 10.0.18334

**Comment by attachmentgenie** [comment]
i have the same problem when the service has been disabled using the checkbox

Steps to reproduce

- create a service (so far i have observed this behavior for rocketchat, mattermost and gitter)
- disable the service using the checkbox
- click the trashcan for the disabled service
- confirm the deletion

Expected behavior

Removal of service

Actual behavior

please wait modal that requires the application to be killed

ENVIRONMENT
Rambox: v0.6.3
OS: Ubuntu 18.04.2
Arch: x64

**Comment by Corchoneitor** [comment]
Still happens in 0.6.7.

When removing disabled service, Rambox keep processing forever. When I restarted Rambox, service was enabled (seems like part of the process of "removing") and then I can remove it without problems.
