### ISSUE TITLE
whatsapp requests browser update

### ISSUE THREAD

**Issue by webmasterzamora** [ramboxapp/community-edition#2134]
WhatsApp works with Google Chrome 36+
To use WhatsApp, update Chrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera.
UPDATE GOOGLE CHROME

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> linux x64 4.4.0-142-generic

**Comment by fvulich** [comment]
Hi @webmasterzamora did you update Rambox to the last version?

**Comment by myelement88** [comment]
Hello, at first thank you for such a great application. I'am using it for work and home. Keep up the good work.

### Expected behavior
Whatsapp service should work w/o asking for a browser update/reload.

### Actual behavior
Since updating Rambox to version 0.6.4 Whatsapp asks on first load for updating the browser. 
![wa-update](https://user-images.githubusercontent.com/20531706/54532577-54499880-4988-11e9-95ac-4dc83942218d.jpg)

### Environment
> Rambox: v0.6.4
> OS: Windows 10 Version: 1803
> Arch: x64
> Browser: Chrome Version 72.x

### Solution
After manually updating Chrome (Menu >Help > About) to version 73.x the update prompt is gone.

**Comment by maxerbox** [comment]
Looks like electron with chromium 73.X is still in beta.
Whatsapp is sort of annoying to remind you to update your browser.
I hope it can be disabled
