### ISSUE TITLE
Not work MS Teams in 0.6.4

### ISSUE THREAD

**Issue by AlexeySHU** [ramboxapp/community-edition#2152]
Hello! Not work calls MS Teams in 0.6.4, but in 0.6.3 work fine
Error: Try a different browser

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> linux x64 4.18.0-16-generic

**Comment by antonc42** [comment]
I'm also experiencing this issue. I use the snap of Rambox and the "Calls" feature of Microsoft Teams was working in 0.6.3, but is not working after updating to 0.6.4.

OS: Kubuntu 18.10 x86_64 4.18.0-16-generic

**Comment by AlexeySHU** [comment]
> I'm also experiencing this issue. I use the snap of Rambox and the "Calls" feature of Microsoft Teams was working in 0.6.3, but is not working after updating to 0.6.4.
> 
> OS: Kubuntu 18.10 x86_64 4.18.0-16-generic

Yes, i use Ubuntu 18.04 LTS, from snap stor version 0.6.4 not work, i manually install from deb package 0.6.3 and work fine

**Comment by antonc42** [comment]
> > I'm also experiencing this issue. I use the snap of Rambox and the "Calls" feature of Microsoft Teams was working in 0.6.3, but is not working after updating to 0.6.4.
> > OS: Kubuntu 18.10 x86_64 4.18.0-16-generic
> 
> Yes, i use Ubuntu 18.04 LTS, from snap stor version 0.6.4 not work, i manually install from deb package 0.6.3 and work fine

You can also use `sudo snap revert rambox` to revert to the previous snap version.

**Comment by maxerbox** [comment]
Weird, we need someone to look at why MS Team is acting like that

**Comment by guzzard** [comment]
Chat history is not loading properly in 0.6.4 either. All chats appear empty even though they have a lot of history.

**Comment by niklasLensing** [comment]
In Windows 1809 no videos calls are possible since 0.6.4

**Comment by arxeiss** [comment]
I just changed in preferences **Override User-agent** to `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134` and calling is back in the game! (OS: Ubuntu 18.10)

However before I tried this: https://github.com/ramboxapp/community-edition/issues/1292#issuecomment-431418444 and it is not working. So I'm not sure where is the problem. But I use Rambox only because of Teams and Outlook Office, I don't care actually.

---

FYI: Even I open teams in latest Chrome in Ubuntu, calling does not work. I have to use [User-agent Switcher](https://chrome.google.com/webstore/detail/user-agent-switcher/dbclpoekepcmadpkeaelmhiheolhjflj) extension

**Comment by leflamm** [comment]
I'm having the same issue (no calls, no video calls) in 0.6.5 and 0.6.6

**Comment by antonc42** [comment]
I am using the snap package on Kubuntu 18.10 and it just updated to 0.6.6. The call feature still does not work by default. I tried changing the global user-agent as @arxeiss suggested and it now works.

It would be nice if it worked without the manual tweak. Does/can Rambox use this user-agent by default for the MS Teams application?
