### ISSUE TITLE
Mac OS X: ⌘+N does not work to change to Nth tab

### ISSUE THREAD

**Issue by adavidzh** [ramboxapp/community-edition#2212]
_Originally posted by @adavidzh in https://github.com/ramboxapp/community-edition/pull/2138#issuecomment-483589510_

### Steps to reproduce

1. Open RamBox on Mac OS
2. Have a few services connected.
3. Try to use `⌘+1`, ..., `⌘+9` to go to different tabs/services.

### Expected behavior

`⌘+N` goes to `N`th tab.

### Actual behavior

Nothing happens

### ENVIRONMENT

> Version: 0.6.6
> Platform: darwin (x64)
> Electron: 4.1.4
> Chromium: 69.0.3497.128
> Node: 10.11.0

### More details

On MacOS X `⌃+PgUp` and `⌃+PgDn` work (also `⌃+ ⇥` works to cycle through tabs).

Unfortunately it seems that `⌘+1`, ..., `⌘+9` do not work as they used to before v0.6.5. `⌘+N` is used in all browsers to go to the `N`th tab (or the last one for `N`=9). Another feature of most browsers is for `⌃+{` and `⌃+}` to move to the previous and next tab respectively. This also does not work. Ditto for `⌃+[` and `⌃+]`.

Can I contribute this?

**Comment by RicoLaaa** [comment]
+1

**Comment by arltmiral** [comment]
+1

**Comment by RicoLaaa** [comment]
this is still an issue with 0.6.9, the focus is either on the app (whatsapp, slack etc) or on rambox. so basically once you start using an app ⌘+N does not work, if you are focused on rambox itself, ⌘+N does work... but shocuts in the apps does not work...
I stopped using rambox because of this, and now use separate apps wich work with shortcuts without having to click anywhere to gain focus.

**Comment by RicoLaaa** [comment]
Will this issue ever be fixed?... no news from 2months..
