### ISSUE TITLE
Rambox does not accept copy and paste for a master password.

### ISSUE THREAD

**Issue by burnsjake** [ramboxapp/community-edition#2300]
Set a master password. Try to paste into the master password box. Doesn't work. Typing the password takes too long and is unreliable.

	
	-
	> Rambox 0.6.8
	> Electron 4.1.4
	> darwin x64 18.6.0

**Comment by Corchoneitor** [comment]
Hi @burnsjake.

From where are you copying that password? Keep in mind that "Copy" is not allowed from "password fields". Maybe your problem is not the pasting, but the copying.

If that is not the case, then maybe it's something about Darwin... because on Windows you can paste passwords in all "master password fields". Let us know :).
