### ISSUE TITLE
Does Not Show Number of Unread Messages in Outlook

### ISSUE THREAD

**Issue by spiralagnus** [ramboxapp/community-edition#2373]
### Steps to reproduce

1. Add either the Outlook or the Outlook 365 app to the Rambox navigation menu.
2. Log in with your account information.
3. Unread messages does not appear in a badge on the left-hand navigation menu.

### Expected behavior

The number of unread messages appears. This was not a problem in Rambox 0.6.7, but it became a problem when I upgraded to Rambox 0.6.9.

### Actual behavior

The number of unread messages does not appear. As show in the image below, I have two unread messages in Outlook, but no badge appears over the navigation menu icon. I've confirmed that this problem exists for both Outlook apps in Rambox.

![Selection_075](https://user-images.githubusercontent.com/31378203/62874034-7f91a300-bcee-11e9-8e2e-b8b88c9638ed.png)

### ENVIRONMENT

> Rambox: v0.6.9

> OS: Xubuntu 18.04

> Arch: x64

**Comment by yafp** [comment]
can confirm this issue.
The inject code seems not to work

**Comment by fvulich** [comment]
It will be fixed in our next release. In the meantime you can inject this JS code to make it work. 

`function checkUnread(){var e=null!==document.querySelector(".ms-FocusZone i[data-icon-name=Inbox]").parentNode.querySelector("span span")?parseInt(document.querySelector(".ms-FocusZone i[data-icon-name=Inbox]").parentNode.querySelector("span span").innerText):0;updateBadge(""===e?0:parseInt(e))}function updateBadge(e){1<=e?rambox.setUnreadCount(e):rambox.clearUnreadCount()}setInterval(checkUnread,3e3);`

**Comment by yafp** [comment]
@fvulich 
is that inject code valid for both services?
