### ISSUE TITLE
Linux back button support

### ISSUE THREAD

**Issue by Pablohn26** [ramboxapp/community-edition#243]
It seems rambox does not support mouse back button. Would be nice the support to make easy Gmail reading (to open and then go back to the email list). 

## 

> Rambox 0.4.1
> Electron 1.3.1
> linux x64 4.6.0-1-amd64

**Comment by saenzramiro** [comment]
I will try to add it for next release.

**Comment by saenzramiro** [comment]
Using mouse back and forward buttons are supported only in Windows ([see here](http://electron.atom.io/docs/api/browser-window/#event-app-command-windows)).

I will add buttons in the menu of the service tab (double click, or in the future right-click hopefully).

**Comment by Pablohn26** [comment]
Would be possible to file a bug / feature request to Electron about this issue in Linux?

**Comment by saenzramiro** [comment]
Sure, it's a feature request not a bug. Feel free to add it to [Electron issues](https://github.com/electron/electron/issues), then share here the link to the issue so I can subscribe to keep in touch.

**Comment by Pablohn26** [comment]
Issue opened [here](https://github.com/electron/electron/issues/6996) :)

**Comment by saenzramiro** [comment]
Awesome! 😉

**Comment by Pablohn26** [comment]
It seems not fixed with the upgrade to rambox 0.4.2

**Comment by MrChick** [comment]
@Pablohn26 works like a charm here

**Comment by Pablohn26** [comment]
@MrChick  which environment?

**Comment by MrChick** [comment]
@Pablohn26 nevermind, sorry. missed the fact that you're on linux

**Comment by saenzramiro** [comment]
@Pablohn26 Only works on Windows sadly. [Read here...](http://electron.atom.io/docs/api/browser-window/#event-app-command-windows)

**Comment by Pablohn26** [comment]
ok @saenzramiro , so we will keep waiting for [this](https://github.com/electron/electron/issues/6996)  issue. Not sure if you prefer to open this (I can edit the title) or open another issue to make a Linux related issue. As you wish.

**Comment by simonwiles** [comment]
As a workaround, can you use something like `xbindkeys` to map your mouse button to the backspace key?  I use this kind of technique all the time, with good results.

**Comment by Pablohn26** [comment]
@simonwiles  backspace key is not working as back action on Gmail (under Rambox), but thanks for the info (I did not know that program and it seems cool)

**Comment by pdp-7** [comment]
Apparently after couple of years this thing is still causing annoyance among laptop users like me.

My Asus Zenbook is rocking Pop_OS! 18.10 and latest Rambox I downloaded yesterday.

Running Rambox mainly to read various forums and blogs and missing back/forward buttons make it rather hard to navigate.

Any plans to add back/forward buttons in the UI. Wavebox for example has them and apparently I don't have any alternative to it, since this renders Rambox unusable time to time for me. I don't want to get back to the site index and navigate my way back to the thread I was reading and all that.

One could bind what ever as workaround, but I have never liked workarounds. Back in the 90's everything was a friggin workaround. Whole linux kernel is one big workaround :)
