### ISSUE TITLE
Rambox for Notes/ToDos, Project Managements, Cloud IDEs, etc.

### ISSUE THREAD

**Issue by saenzramiro** [ramboxapp/community-edition#244]
Today I was thinking that maybe we can expand Rambox to allow different profiles. Today only allow by default Messaging and Emailing apps, but some users add Custom Services for Notes like Evernote, or Project Management like Trello.

The idea is to configure Rambox to add categories (left side of the picture) to classify their services.

If there is one category (Default), the left tabbar it will be hidden, so Rambox will be like now. But if the user creates a new category called "Notes", he can add all services related to Notes there. Also he can create a "Personal" or "Business" category to separate, and enable don't disturb or mute all by category.

![rambox](https://cloud.githubusercontent.com/assets/2694669/17750126/16a065dc-6497-11e6-92ae-d099cc003ded.png)

Thumb up or thumb down for the idea.
UI/UX collaboration will be appreciated.

Related #74

**Comment by stonfute** [comment]
Possibily to include self-hosted services ? (wekan, ...)

**Comment by saenzramiro** [comment]
@stonfute Of course! :wink:

**Comment by Stele77** [comment]
Absolutely!
I think this is a logical step, and would make Rambox a true Killer Application! I today already use it this way, with my Cloud and other Webservices. 
Not following this course would waste the biggest potential of this App IMHO..
:)

**Comment by TriiNoxYs** [comment]
Good idea, it would be very interesting ! :+1:

**Comment by pcdog** [comment]
:+1: Yeah, I would support that! I am just starting to get worried about memory consumption ;) It already gets my notebook to swap...

**Comment by franciscoluiz** [comment]
Good idea. +1

**Comment by bendikl** [comment]
Hey guys, great great idea, I suggested something similar + more today in https://github.com/saenzramiro/rambox/issues/422

I think the right tab bars are smart due to many apps having extra widespace horizontally, the only thing is that I get damn dizzy reading sideway, are there any successfull good UX apps that use the sideways approach?

Let`s also sketch up a horizontal approach and see if that would look better, I also have some ideas on how the project/section area could be on top and take little space, expanding on mouse hover to select another section.

Regarding @pcdog `s comment on RAM consumption we just got news the new v8 engine will consume 50% less (or so they say). Additionally we could explore the opportunity of a checkbox for sleeping services/tabs that goes to sleep after X time, for example memory consuming ones that are only used infrequently.

**Comment by gimntut** [comment]
My ideas:
![1 - standart state](https://cloud.githubusercontent.com/assets/1645084/20453829/4909382c-ae53-11e6-8e75-b446ccf9480b.jpg)
![2 - show tabs](https://cloud.githubusercontent.com/assets/1645084/20453830/4b6bb7b6-ae53-11e6-8d1b-133794c4a7f6.jpg)
![3 - show groups](https://cloud.githubusercontent.com/assets/1645084/20453831/4d142440-ae53-11e6-9771-a0184d3ad229.jpg)

1. Group is not category. In group can be any WebApp
2. In "Show webapp sidebar" mode, Logo change to Options button, under mouse cursor.
3. May be need logo for group from imoji? Then groups can be a lot.
4. May be enable/disable group for save RAM?
5. In compact mode need hints for buttons.

**Comment by saenzramiro** [comment]
@gimntut Awesome work! I had a similar idea, so probably I will do something like that.

I will try to make a design and share it here before start doing it.

**Comment by 88scythe** [comment]
What's the status of this one?
(No pressure, just a curious question.)

**Comment by saenzramiro** [comment]
We couldn't started yet, but hopefully in the next months we can release it.

**Comment by RichiCoder1** [comment]
This would be terrific. Currently using custom services to emulate this with Azure Portal & VSTS.

**Comment by nmat** [comment]
@RichiCoder1 you can support this by checking out: http://rambox.pro/100/

**Comment by thedonquixotic** [comment]
Been almost a year since this was last commented on. What's the status? Can I contribute in any way? I'm a professional UX Designer and I'd like to contribute if I knew that progress would actually be made. Maybe if I could pair with one of the lead contributors to this project?
