### ISSUE TITLE
Editing settings of _Custom Service

### ISSUE THREAD

**Issue by schousda** [ramboxapp/community-edition#2448]
Hello,
when i try to change the settings of a custom service, Rambox tells me, that the URL is wrong, even if i didn't touch it.
I have to delete the URL and retype it. Then it works.
![grafik](https://user-images.githubusercontent.com/21222928/69215455-0d8ced80-0b6a-11ea-9a23-419feebe9194.png)

Rambox: v0.7.X
OS: Windows 10
Arch: x64

**Comment by saalkom** [comment]
This happened to me when creating a custom service in 0.7.1. One of the forward-slashes after "https:" was deleted when I pasted the URL into the URL box, but the same didn't happen with the logo box.

I can't test on 0.7.2 because it's not available through `snap refresh rambox` yet. Anyone have any idea when it will be?

**Comment by fvulich** [comment]
duplicate #2476
