### ISSUE TITLE
Skype blank screen after update Rambox 0.7.1

### ISSUE THREAD

**Issue by nghehuavan** [ramboxapp/community-edition#2457]
Skype blank screen after update Rambox 0.7.1
        Checked : Rambox 0.7.0 open skype ok

	
	-
	> Rambox 0.7.1
	> Electron 7.1.1
	> win32 x64 10.0.17134

**Comment by hnkumar** [comment]
Facing the same problem.

Version: 0.7.1
Platform: linux (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1
Snap: revision 9

I'm using as a snap application.

**Comment by edikici** [comment]
The same issue here. When I delete and re-add the Skype service, I get a notification instead of a blank screen, saying:

"We can't sign you in
Your browser is currently set to block cookies. You need to allow cookies to use this service.
Cookies are small text files stored on your computer that tell us when you're signed in. To learn how to allow cookies, check the online help in your web browser."

Hope it helps.

**Comment by fvulich** [comment]
We apologize for this inconvenience.
We already identify the error, and we are working on a fix.

**Comment by fvulich** [comment]
We released 0.7.2 which includes the fix for this issue.
