### ISSUE TITLE
Clicking links from Google Calendar event descriptions opens a blank chrome browser tab

### ISSUE THREAD

**Issue by balasankarc** [ramboxapp/community-edition#2526]
### Steps to reproduce

1. Open Google Calendar
2. Add an event with a link in the description
3. Click on the event, and click on the link

### Expected behavior

The link gets opened with the default browser of the system.

### Actual behavior

The link is not opened in default browser, but a blank chrome window opens.

### ENVIRONMENT

> Rambox: v0.7.3

> OS: Debian

> Arch: x64

**Comment by fvulich** [comment]
![image](https://user-images.githubusercontent.com/46904390/71261556-6d6ae580-231c-11ea-8d92-86e9899505c3.png)
We're investigating this issue. In the meantime you can right-click the link and click in open link

**Comment by balasankarc** [comment]
@fvulich Thanks for the workaround.

**Comment by tonytamps** [comment]
Usually this behaviour happens when chrome has performed an update in the background. 
I bet you have the arrow in Chrome saying there is an update ready to install.

Something happens where the active running process is no longer the launched process and it opens a new tab. Used to happen to me when clicking links in Slack.

You should restart (and update) Chrome to fix it. I think there is a way to launch the link differently to avoid this but I don't really think it's a Rambox problem.

**Comment by fvulich** [comment]
Fixed in v0.7.9
