### ISSUE TITLE
HiDPI Issue

### ISSUE THREAD

**Issue by RogerMontilla** [ramboxapp/community-edition#2539]
I have a Debian distribution and I have a Full HD screen. So I need to scale the DPI to be able to see the app correctly

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> linux x64 4.19.0-6-amd64

**Comment by piemonkey** [comment]
I think this is a Chromium/Electron issue because I don't think I've seen an Electron app work automatically. You can work around it by running Rambox with `--force-device-scale-factor=2` (or any floating point value). There's good information on ArchWiki: https://wiki.archlinux.org/index.php/HiDPI#Chromium_/_Google_Chrome

**Comment by fvulich** [comment]
duplicate #2404 & #250
