### ISSUE TITLE
Firefox containers: the end of Rambox and the likes?

### ISSUE THREAD

**Issue by jerry1970** [ramboxapp/community-edition#2558]
With Firefox's recently added tab containers, I can reach the same goal of having a couple of tabs with my favourite web clients open, even with two WhatsApp tabs with different account.

An added bonus is with the Stylish addon it's a lot easier to apply custom styling. Also, links in these clients are opened in the same window but a different tab. Desktop notifications also work. (Except for Messenger but Facebook has been a pain in the ass anyway.)

To have my regular Firefox for other work in a separate window, I made a new profile in Firefox for the web clients window and open Firefox with that profile (`firefox -P <ProfileName>`). Links from other windows are opened in my regular Firefox window (the default profile) or a new window.

I have no doubt other browser will follow with containers like this.

Does this mean the end of Rambox, Franz, Station, and the likes?

**Comment by saenzramiro** [comment]
Non-power users can achieve similar functionality as Rambox CE by using browsers equipped with multiple properly configured add-ons.
Rambox users choose it because it is an application specifically created for organizing their workspace, and therefore they enjoy the convenience of easily achieving that goal and not worrying about having to do it more than once.
From what I can see, this new "Multi-account" add-on is primarily geared towards security use cases.

Of course, I am only referring to Rambox CE, given that the Pro version comes packed with many other features that make setting up and managing your workspace even better.
