### ISSUE TITLE
Skype - sharing doesnt work

### ISSUE THREAD

**Issue by badsector3** [ramboxapp/community-edition#2660]
### Steps to reproduce

1. Skype sharing doesnt work on MAC OSX Catalina 10.15.4. I can see somebody sharing but I cannot share

### Expected behavior

Be able to share my screen

### Actual behavior

Nothing happens when I press the sharing button

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Catalina 10.15.4

> Skype: 8.58.0.93

> Arch: x64

**Comment by fvulich** [comment]
We're investigating this issue. Please share with us any information that seems relevant for you.

**Comment by joaotomasrobalo** [comment]
It doesn't work on Microsoft Teams either. Mac OS.

Is it possible to be because Rambox does't "ask" for permissions to screen record? For example to be able to share my screen on a google meeting (using google chrome for example) I had to grant the google chrome app this permission. 

<img width="667" alt="Screenshot 2021-02-12 at 12 00 50" src="https://user-images.githubusercontent.com/43414610/107765541-f5cef580-6d29-11eb-9876-c41e46e59d07.png">

If I untick any of those apps from the screen recording permissions, the "share screen" will stop working (either on a google meeting on chrome or a zoom call on zoom). I assume Rambox needs to be here for the system to allow screen sharing. 

That permission is a requirement for sure.

Now my assumption that could be wrong. -> The problem is that for us to add Rambox on the granted permissions to screen record apps list, the application needs to "ask" first and it seems not to be happening because I don't see Rambox here, even when I try to share my screen.

Does this makes sense?
