### ISSUE TITLE
Keep getting logged out of outlook

### ISSUE THREAD

**Issue by kevinunger** [ramboxapp/community-edition#2668]
# Steps to reproduce

1. Add outlook to Rambox
2. Login to outlook
3. Reboot Rambox
4. Need to re-login into outlook (Only have to input the mail-address again, not the password) 

### Expected behavior

Stay logged in to outlook.

### Actual behavior

Need to re-login into outlook

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Windows 10 1909

> Arch: x64

**Comment by fvulich** [comment]
Could you try deleting the Outlook app and adding it again?

**Comment by kevinunger** [comment]
I deleted the outlook app and re-logged in. Unfortunately, it does not resolve the issue.

**Comment by fvulich** [comment]
Please, try, again, deleting the Outlook app and adding it and be sure to check this box before entering your password.
![image](https://user-images.githubusercontent.com/46904390/80213505-a808c580-860f-11ea-8406-36d144bb5d33.png)
If that doesn't do the trick, could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

If you are a Linux user you could try different packages because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)
