### ISSUE TITLE
Linkedin Scrolling Issues on main page and other pages

### ISSUE THREAD

**Issue by jsnagi** [ramboxapp/community-edition#2683]
### Steps to reproduce

1. Add Linkedin App
2. Go to Home, and there is no Scroll Bar.  You can not scroll thru the page.
3.  I'm using Rambox Pro on Win10x64 Pro

See attached pic with annotations.

[https://imgur.com/pp5oDDO](url)

### ENVIRONMENT

> Rambox Pro: v1.7.5

> OS: Win10 Pro

> Arch: x64

**Comment by fvulich** [comment]
Hi, it seems that you are using LinkedIn Messenger app instead of the LinkedIn app. Please add LinkedIn app and you won't have this issue.
![image](https://user-images.githubusercontent.com/46904390/80212562-15b3f200-860e-11ea-9448-8efe9b3c2fcf.png)
By the way, this support channel is for Rambox CE users. If you are using Rambox Pro, please use our [Help Desk](https://rambox.freshdesk.com/) to report your problems, and we will help you there.

**Comment by jsnagi** [comment]
Thank you.... I just added custom website and it worked..... but will try the Linkedin App.
