### ISSUE TITLE
Учетные данные

### ISSUE THREAD

**Issue by HermesConrad** [ramboxapp/community-edition#2685]
Здравствуйте! Почему у меня в программе не сохраняются учетные данные логин-пароль? синхронизация есть, но данные каждый раз приходится вводить заново. 
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 ia32 6.1.7601

**Comment by fvulich** [comment]
> Hello! Why my login-password credentials are not stored in my program? There is synchronization, but the data must be re-entered each time.

Which apps are not retaining the login information? Could you try deleting and adding them again?

**Comment by HermesConrad** [comment]
все приложения не сохраняют данные. даже после нового ввода логин-пароль и перезагрузки компьютера. Возможно, это связано с ошибками операционной системы?

**Comment by HermesConrad** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/24565268/80217126-9697db80-8658-11ea-9f00-a99018678836.png)
![Screenshot_2](https://user-images.githubusercontent.com/24565268/80217131-98619f00-8658-11ea-807f-afbc8b5c4117.png)
![Screenshot_3](https://user-images.githubusercontent.com/24565268/80217133-9992cc00-8658-11ea-8409-76c8bdc88020.png)

**Comment by fvulich** [comment]
Could you try doing a Clear cache & a Clear Storage? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

If you are a Linux user you could try different packages because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)

**Comment by HermesConrad** [comment]
Спасибо! Надеюсь, поможет. Удачи!
