### ISSUE TITLE
Update not applicable 0.7.5

### ISSUE THREAD

**Issue by Trucmachinchose** [ramboxapp/community-edition#2688]
Hi Team, the last update dont installing...always the same thing when I restart Rambox..
Thank's for a solution...
Patrick 
![Rambox](https://user-images.githubusercontent.com/64332213/80290907-d7eec080-8716-11ea-836b-bb26eb638b8c.PNG)

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> win32 x64 6.1.7601

**Comment by fvulich** [comment]
Could you try doing a Clear cache & a Clear Storage? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.
