### ISSUE TITLE
Slack attach files problem

### ISSUE THREAD

**Issue by vallsjm** [ramboxapp/community-edition#2701]
The app window close on Slack when try to attach/upload a file from the computer.

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 5.4.0-28-generic
        > Ubuntu 20.04

**Comment by fvulich** [comment]
Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

If you are a Linux user you could try different packages because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)

**Comment by vallsjm** [comment]
Clear Cache && Clear Local Storage doesn't work.

Rambox from Ubuntu Software in Ubuntu 20.04 LTS doesn't work (Well, work but with upload problems).

But, uninstall and install Rambox directly without Ubuntu Software is the solution.

Thank u!!
