### ISSUE TITLE
Notification icon disappears

### ISSUE THREAD

**Issue by sleepyspider1** [ramboxapp/community-edition#2703]
The icon near the clock disappears and turn to empty square.
Kill explorer so icons refresh. It won't refresh.

-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.
