### ISSUE TITLE
Totally blank

### ISSUE THREAD

**Issue by cwharts** [ramboxapp/community-edition#2722]
Opened and reopened but no change.
![blank](https://user-images.githubusercontent.com/16431419/83141055-a91c8f00-a0b4-11ea-91d6-3cd362a06e4b.png)

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

If you are a Linux user you could try different packages because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)

**Comment by cwharts** [comment]
Prior to your response, I had restarted and it resolved the problem. Thanks
for the additional information. Please close the ticket.

Thanks,
Chris
