### ISSUE TITLE
No notifications are shown, even in version 0.7.4. Which version can actually make them work?

### ISSUE THREAD

**Issue by 613TheEvil** [ramboxapp/community-edition#2732]
-
	> Rambox 0.7.4
	> Electron 7.1.12
	> win32 x64 6.1.7601

**Comment by 613TheEvil** [comment]
I get the same error whenever I try to install a different version, even the latest one. Perhaps this would explain why I can't fix the notification problem? I don't see the icon turn from white to red no matter what I try, please help. This is the error message I get, even though the program runs "normally":

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Rambox-0.6.6-win.exe
  Application Version:	0.6.6.6
  Application Timestamp:	5a6fed7c
  Fault Module Name:	StackHash_80d9
  Fault Module Version:	6.1.7601.18247
  Fault Module Timestamp:	521ea8e7
  Exception Code:	c0000374
  Exception Offset:	000ce753
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1032
  Additional Information 1:	80d9
  Additional Information 2:	80d9a8b4e0455e46f3a01f421afe5e1b
  Additional Information 3:	9421
  Additional Information 4:	9421f6074591501034695d0af323670e

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by 613TheEvil** [comment]
I made a clean install of version 0.7.3, nothing, no salvation...

**Comment by fvulich** [comment]
We can't understand your issue, could you elaborate a bit further on your issue?

Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

If you are a Linux user you could try different packages because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)

**Comment by 613TheEvil** [comment]
It works fine for about 2 weeks now, I am using the latest version of Rambox. Sorry if I did not post here earlier, I wanted to be sure first and time passed...

**Comment by fvulich** [comment]
Glad to hear that! I'm gonna close this ticket, feel free to open a new one if the issue reappears.
