### ISSUE TITLE
the system has become so slow

### ISSUE THREAD

**Issue by Thyrius** [ramboxapp/community-edition#2748]
Hello guys, first of all thanks for this mega app !!

The following tabs are currently active in my app:
- Google Calendar
- WhatsApp
- Messenger (Facebook)
- 5x telegram

Since the last update, the system has become so slow that it hardly writes any text fluently. It stops constantly, does not go any further. Several times I had to close and restart the app via the task manager.

My computer system:

HP Z440 Workstation Intel Xeon E5-1650 v4 - 6 x 3.60 GHz | 32 GB RAM | NVIDIA Quadro K1200 | 256 GB SSD | 1024 GB SSD | 4x 1024 GB HDD | Win 10 Pro

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

**Comment by Thyrius** [comment]
Thanks for the tip, I will implement it and report.
I won't be back in the office until Monday, so I'll report back tomorrow.
Thanks

**Comment by Thyrius** [comment]
It didn't help.
I reinstalled it, it's fine now.
I don't know what it was.
Thanks for your support.
