### ISSUE TITLE
Bug: Tab change does not change focus

### ISSUE THREAD

**Issue by sid3windr** [ramboxapp/community-edition#2754]
### Steps to reproduce

1. Go to Whatsapp (or other service) tab, select the text input box
2. Go to Slack  (or other service) tab, start typing
3. Text does not appear in Slack inputbox, but in Whatsapp inputbox - invisible as it's not the current tab

### Expected behavior

(Input box on) the currently active tab should have focus - at the very least (input box on) inactive tab should NOT have the focus.

### Actual behavior

Focus remains where it is even when switching tabs.

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Windows 10

> Arch: x64

**Comment by fvulich** [comment]
Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

**Comment by sid3windr** [comment]
This is a brand new install, it was installed on the 5th of July and 5 services were added (Whatsapp, Slack, Android Messages, Discord, Skype) and the issue surfaced. I don't think un-/reinstalling and doing exactly the same will make a difference in that regard...

I can try though, if you really feel that will somehow toggle something unexpected?

Thanks!

**Comment by sid3windr** [comment]
Actually restarting the app a few times seems to have solved this issue for me! Closing this, at least until it pops up again...
