### ISSUE TITLE
100% GPU usage 

### ISSUE THREAD

**Issue by samuelgfeller** [ramboxapp/community-edition#2755]
### Steps to reproduce
I couldn't figure out the exact steps to reproduce to trigger the issue since it happends "sometimes" but when it happends its very annoying and a restart of rambox isn't enough  
1. I had Rambox opened on my computer and did nothing special

### Expected behavior
A "normal" use of GPU

### Actual behavior
It uses maximum GPU I can get sometimes (multiple times in a week). 
![Image with issue](https://i.imgur.com/hXbySH1.png "Task Manager")

Which makes the fans go crazy on my computer. Quitting rambox and start the process again doesn't fix the issue. It quickly goes up to 100% again. I think restarting the computer fixes it or what I do is close it and wait a few hours and open it later again in hope that it wont happen again. 

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Windows 10 Home 1909

> Arch: x64

> Hardware: Dell XPS 9500 i7 10th Gen., GeForce GTX 1650 Ti
It uses the integrated intel graphics not the GTX (explicitly configured in 3d settings to use integrated graphics) and NVIDIA GPU-Activity control doesn't mention any activity on the GTX.

I know this is a very vague bug report and Im sorry I couldn't figure out the steps I had to do to trigger this issue but maybe one of you will recognize it and help me out. Probably its Electron that is making the pain but I didnt find much on the internet about it...

It's probably related to #538 but I dont think its the same since it apperantly doesnt switch to the high performance GPU. I didn't find where to disable hardware acceleration on rambox.

**Comment by fvulich** [comment]
It seems that an app inside Rambox CE is consuming a lot of GPU, could you try to do this? Once you notice that Rambox CE is consuming an abnormal amount of resources, try to disable apps one by one to see if one of them is the culprit.

If that doesn't do the trick, could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.
