### ISSUE TITLE
Slack destroyed Rambox

### ISSUE THREAD

**Issue by HechtYehuda** [ramboxapp/community-edition#2777]
I added my Slack channel. The Slack channel never loaded and now all Rambox displays is a teal screen--no channels or anything else.

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 5.4.0-42-generic

**Comment by fvulich** [comment]
Could you elaborate  a bit further? I'm using (several) Slack in Rambox CE without issue tested in macOS, Windows and Ubuntu. 

Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

If you are a Linux user you could try different packages because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)
