### ISSUE TITLE
OSX Catalina keeps saying it needs permissions for microphone and camera

### ISSUE THREAD

**Issue by robross0606** [ramboxapp/community-edition#2800]
### Steps to reproduce

1. Install Rambox CE on Mac OSX Catalina
2. Start Rambox
3. Observe notification about Microphone and Camera permissions.  Click "Grant permissions".  Nothing happens.
4. Completely close Rambox.
5. Start Rambox again.
6. Observe notification about Microphone and Camera permissions.
7. Go to OSX Security & Privacy Settings.  Note that there are no Rambox registered permission requests for Microphone or Camera.

### Expected behavior

When opening Rambox, it should provide a notification at the top that says "Rambox CE needs permissions to use Microphone and Camera for the apps."  The button for "Grant permissions" should at least bring the user to the OSX Security & Privacy settings so that the user can grant permissions for Microphone or Camera where Rambox has registered permission requests.

The option under Help menu in Rambox for "Grant Microphone and Camera permissions" should do the same thing.

### Actual behavior

When opening Rambox, it keeps providing a notification at the top that says "Rambox CE needs permissions to use Microphone and Camera for the apps."  There is a button for "Grant permissions", but clicking it does nothing.  Manually going to Security & Privacy settings shows that no permissions requests have even been registered for Rambox under Microphone or Camera.

The option under Help menu in Rambox for "Grant Microphone and Camera permissions" also does nothing.

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Mac OSX 10.15.6

> Arch: x64

**Comment by fvulich** [comment]
Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.
