### ISSUE TITLE
Cant paste images in 0.7.6

### ISSUE THREAD

**Issue by c4tz** [ramboxapp/community-edition#2808]
### Steps to reproduce

1. Copy an image from somewhere, for example Chromium or Rambox itself
2. Paste it into any Rambox tab, for example Whatsapp or Discord

### Expected behavior

Before the update today (had 0.7.5 before), I could paste an image directly into the text box and send it.

### Actual behavior

Rambox freezes completely for a few seconds, I am not able to type or switch the service anymore. Afterwards there is no image pasted.

### ENVIRONMENT

> Rambox: v0.7.6
> OS: Arch Linux on 5.8.5 Kernel + X11
> Arch: x64

**Comment by fvulich** [comment]
Couldn't reproduce  your issue. It works as it should in Ubuntu 18.04 with snap package. You could try different packages because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)

**Comment by c4tz** [comment]
Thank you for the response. I'm already using the `rambox-bin` package you linked, unfortunately the [only other one](https://aur.archlinux.org/packages/rambox/) has not been updated by its maintainers yet. Will try when it is, though.

**Comment by SkylerLLewis** [comment]
This issue is also happening for me in the discord app on Ubuntu 20.04, exactly as described.

**Comment by c4tz** [comment]
I just experienced the same behaviour in the Signal Desktop Client, so this issue seems to be related to electron, not Rambox.
