### ISSUE TITLE
Whatsapp broken

### ISSUE THREAD

**Issue by Kurocon** [ramboxapp/community-edition#2811]
### Steps to reproduce

1. Add whatsapp and load the page

### Expected behavior

Whatsapp Web appears

### Actual behavior

Facebook error message, see the image below. Included is the failing network request as well. If loaded in a normal web browser (Firefox in my case), it loads and works normally.

![image](https://user-images.githubusercontent.com/1193988/92254691-8f6bbe80-eed1-11ea-9880-8b9c03c5c94a.png)

### ENVIRONMENT

> Rambox: v1.3.2 (Pro)

> OS: Arch Linux, kernel 5.8.5-arch1-1

> Arch: x64

**Comment by fvulich** [comment]
We apologize for this inconvenience. We made some changes in the WhatsApp configuration and now it is working now as it should. Please restart Rambox Pro in order to get them. Also, this support channel is for the CE users. If you are using Rambox Pro, please use our [support portal](https://rambox.freshdesk.com/) to report your problems, and we will help you there.
