### ISSUE TITLE
Unable to authenticate with google

### ISSUE THREAD

**Issue by renatofmsoares** [ramboxapp/community-edition#2819]
When I try to authenticate with google, a screen appears saying:

Couldn't sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

However, I cannot change or update the Rambox's internal browser.

	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 5.4.0-42-generic

**Comment by renatofmsoares** [comment]
![image](https://user-images.githubusercontent.com/24680037/92536517-46d53d80-f210-11ea-87e0-68ae41350af6.png)

**Comment by jerichosy** [comment]
Upgrade to 0.7.6, that fixed it for me.

**Comment by fvulich** [comment]
This issue has been fixed in v0.7.6 you can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Comment by roa-nyx** [comment]
Hey, love your app, but thought you should know.

I just downloaded and installed Rambox a couple of days ago, and I checked and it's 0.7.6.

I loved that Rambox ran at like 50% of the RAM usage I'm used to with my previous solution, and that I can actually sign into Slack with the latest version.

So instead of "logging in" I tried to "sign up" through the app and got this same error. I got to this issue, and was trying to reproduce the issue so I could send a new screenshot, but it suddenly started working.

Just thought you should know it seems there is still some conditions where this might still happen.
