### ISSUE TITLE
DISCORD SCREEN SHARING

### ISSUE THREAD

**Issue by FreakyWaves** [ramboxapp/community-edition#2842]
### Steps to reproduce

1. Open Rambox
2. Start a call / join a call in a server
3. try to press the share screen button
4. No window appears

### Expected behavior
Being able to share my screen

### Actual behavior
No Window appears, making it impossible to share my screen

### ENVIRONMENT

> Rambox: v0.7.6

> OS: Windows 10 HOME 20H2 19042.508

> Arch: x64

# Workaround 
I found using an external video capture / virtual capture device software, and using the camera does the job, but it would be nice if it was fixed

**Comment by fvulich** [comment]
Thanks for the feedback, could you share your workaround with us? Steps, some screenshots, or even better a video. For the video we recommend www.loom.com

**Comment by FreakyWaves** [comment]
Using Logitech Capture software

**Comment by liondy** [comment]
I'm using Discord for Rambox in Ubuntu 20.04 and yes, if I want to share my screen in voice channel, no window open, I want to be able to share my screen. Can somebody fixed this issue? Thank you

**Comment by parasudilip** [comment]
Currently I am using OBS as a capture source for screen sharing. It works, but the inbuilt screenshare dosent work.

**Comment by JL102** [comment]
Screen sharing doesn't work on Skype on Rambox either.

**Comment by joaotomasrobalo** [comment]
It doesn't work on temas either. Mac OS.

Is it possible to be because Rambox does't "ask" for permissions to screen record? For example to be able to share my screen on a google meeting (using google chrome for example) I had to grant the google chrome app this permission. 

<img width="667" alt="Screenshot 2021-02-12 at 12 00 50" src="https://user-images.githubusercontent.com/43414610/107765541-f5cef580-6d29-11eb-9876-c41e46e59d07.png">

If I untick any of those apps from the screen recording permissions, the "share screen" will stop working (either on a google meeting on chrome or a zoom call on zoom). I assume Rambox needs to be here for the system to allow screen sharing. 

That permission is a requirement for sure.

Now my assumption that could be wrong. -> The problem is that for us to add Rambox on the granted permissions to screen record apps list, the application needs to "ask" first and it seems not to be happening because I don't see Rambox here, even when I try to share my screen.

Does this makes sense?

**Comment by myangelaku** [comment]
Issue still occuring, Windows 64bit here

> 
> 
> Currently I am using OBS as a capture source for screen sharing. It works, but the inbuilt screenshare dosent work.

That's a nice workaround, but with this method, the audio won't get shared with it.

**Comment by JL102** [comment]
> It doesn't work on Microsoft Teams either. Mac OS.
> 
> Is it possible to be because Rambox does't "ask" for permissions to screen record? For example to be able to share my screen on a google meeting (using google chrome for example) I had to grant the google chrome app this permission.

I would guess that screen sharing on Mac OS and on Windows require different API calls. I really hope a developer can look into this sometime soon.

**Comment by JL102** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture

In Chromium, executing `navigator.mediaDevices.getDisplayMedia()` in the console opens the standard screen share prompt.  
If I hit Cancel, I get this error: `Uncaught (in promise) DOMException: Permission denied`

Whereas in a Rambobx tab, if I execute that command in the console, it immediately rejects and returns that DOMException: Permission denied message. Same happens if you click the Share Screen button on Discord (in Rambox).

Something is wrong with the Screen Capture API in Rambox that causes it to immediately reject permission.

**Comment by ark02** [comment]
Having the same issue with any screenshare apps

**Comment by bkzshen** [comment]
Rambox 0.7.9 still can't share screen on Discord

**Comment by Chinmay726** [comment]
Rambox 0.7.9 2022 still cant screenshare, pls fix it

**Comment by teras** [comment]
Hello, since I do have this issue still with version 0.7.9 of Rambox, by closing the issue does it mean that this issue is fixed?
