### ISSUE TITLE
Rambox 0.76 crashes frequently

### ISSUE THREAD

**Issue by ajaysimha** [ramboxapp/community-edition#2844]
### Steps to reproduce

1. OS is Fedora 32
2. Download Rambox AppImage
3. Enable Android Messages, Whatsapp, Microsoft Teams and Linked Messages

### Expected behavior
works normally after starting and stays up (does not crash)

### Actual behavior

Works normally and suddenly the entire Rambox window disappears.
You will have to restart it.

### ENVIRONMENT

Fedora 32

> Rambox: v0.7.6

> OS: Fedora 32

> Arch: x64

**Comment by pmahnke** [comment]
Me too on OS: Ubuntu 20.04

**Comment by fvulich** [comment]
It seems that an app inside Rambox CE is crashing, could you try to do this? Try disabling apps one by one to see if one of them is the culprit.

If that doesn't do the trick, could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

If you are a Linux user you could try different packages because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)
