### ISSUE TITLE
strange on Whatsapp files attach interface

### ISSUE THREAD

**Issue by 64m64n9bils** [ramboxapp/community-edition#2847]
-
	> Rambox 0.7.6
	> Electron 7.2.4
	> linux x64 5.8.11-1-MANJARO

**Comment by fvulich** [comment]
Could you try a different package because depending on your Linux distribution some are better than the others? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)

I recommend trying the AUR first for Manjaro
