### ISSUE TITLE
Have to log in every time I use Rambox, it does not remember my passwords

### ISSUE THREAD

**Issue by Ed-Zero** [ramboxapp/community-edition#2864]
Hello, my issue is that I am forced to login in to discord and hangouts through Rambox every time. This was not always the case as I had to reset my Win10 system yesterday. Before that, I had no issues, just type in the email and password once and I was good to go. Now, having to log in every time to every chat program is tedious. Is there a fix for this?

Thanks

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19041

**Comment by fvulich** [comment]
Could you try deleting those apps and adding them again?

If that doesn't do the trick, could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

If you are a Linux user you could try different packages because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)
