### ISSUE TITLE
Rambox  does not load the messengers in start. 

### ISSUE THREAD

**Issue by d1063735** [ramboxapp/community-edition#2868]
-
	> Rambox 0.7.7
	> Electron 7.2.4
	> linux x64 5.4.0-52-generic

**Comment by fvulich** [comment]
Could you elaborate a bit further about your issue? What messenger services didn't load?

In the meantime, you could try doing a Clear cache & a Clear Storage. Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)

If that doesn't work either, you could  try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

If you are a Linux user you could try different packages because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)
