### ISSUE TITLE
No indicator 

### ISSUE THREAD

**Issue by oneiroi-el** [ramboxapp/community-edition#2886]
I don't have the rambox's indicator  in the top bar of gnome
( I use fedora 33)
Thanks for reading my message

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> linux x64 5.8.18-300.fc33.x86_64

**Comment by fvulich** [comment]
I don't fully understand your issue, but I think you meant that there's no tray icon or something like that.  Could you try with a different package because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)
