### ISSUE TITLE
In app browser does not resize with Rambox Window 

### ISSUE THREAD

**Issue by glyko54** [ramboxapp/community-edition#2900]
I'm running the latest version of Rambox on a Surface Book 2 Running Windows 10. When running in a "rectangular" window, Rambox looks perfect. 
![image](https://user-images.githubusercontent.com/62068242/99954895-be345b00-2d83-11eb-99d3-7e147db3882b.png)

But when you resize the window (put in full screen for example), the in-app browser displaying the different services fails to adapt accordingly. I am left with these enormous white borders on the top and bottom. 
![image](https://user-images.githubusercontent.com/62068242/99955263-4dda0980-2d84-11eb-8007-5308517995a9.png)

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19042

**Comment by fvulich** [comment]
That's really odd. Could you try doing a Clear cache & a Clear Storage? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

**Comment by glyko54** [comment]
It's fixed now, thank you! It seems it was just a temporary bug.
