### ISSUE TITLE
Literally nothing loads

### ISSUE THREAD

**Issue by OrangeKale64** [ramboxapp/community-edition#2911]
Literally nothing loads. I can sign in but once I am signed in the page goes white. I have restarted multiple times and even reinstalled the program. Please help

Edit :
I also tried clearing the cache and local storage

> Rambox 0.7.7
> Electron 7.2.4
> win32 x64 10.0.19042

**Comment by OrangeKale64** [comment]
Steam loades fine.
Hangouts is just blank.

**Comment by OrangeKale64** [comment]
Found this in the console

>The service fail at loading https://accounts.google.com/signin/v2/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&service=mail&sacu=1&rip=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin Event {isTrusted: false, errorCode: -102, errorDescription: "ERR_CONNECTION_REFUSED", validatedURL: "https://mail.google.com/accounts/SetOSID?authuser=…04kU0O0mOQQ6VOFgM57bq6GCqPopSoN45Ye--fyC4Vx3aVh_g", isMainFrame: true, …}

**Comment by fvulich** [comment]
Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.
