### ISSUE TITLE
Google Duo: can login, but not reach the site due to an error

### ISSUE THREAD

**Issue by dakotawhitevalley** [ramboxapp/community-edition#2914]
### Steps to reproduce

1. Create new service tab for Google Duo
2. Login

### Expected behavior
Be presented with Google Duo's web version.

### Actual behavior
Presented with an error message:
![image](https://user-images.githubusercontent.com/4442088/100571085-42b13d00-32a0-11eb-8d6c-82cb74401732.png)

### ENVIRONMENT
> Rambox: v0.7.7
Platform: win32 (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

> OS: Windows 10 Professional - Version 20H2 (Build 19042.630)

> Arch: x64

**Comment by fvulich** [comment]
We're investigating this issue.

**Comment by Len-B** [comment]
This issue is still causing problems. I have tried numerous times to create a  Duo entry in Rambox (on two different PCs) and it always gives me the same error as the original poster. It seems that this failure is widespread and just needs your team to create a Gmail account and you'll almost certainly be able to reproduce it!

**Comment by Len-B** [comment]
What further information do you require? I'd like to help so that this could be resolved.

**Comment by Len-B** [comment]
Hello,

I've just added a comment offering to help. I'm struggling to understand 
what info you require as the issue is readily reproducible.

Please let me know what further info you require.

Len

------ Original Message ------
From: "no-response[bot]" ***@***.***>
To: "ramboxapp/community-edition" ***@***.***>
Cc: "Len-B" ***@***.***>; "Comment" 
***@***.***>
Sent: 11/06/21 16:41:56
Subject: Re: [ramboxapp/community-edition] Google Duo: can login, but 
not reach the site due to an error (#2914)

**Comment by fvulich** [comment]
It seems that Google Duo doesn't like Electron as a browser, and we couldn't find  a workaround for this.
