### ISSUE TITLE
Play audio messages when "DO NOT DISTURB" is on

### ISSUE THREAD

**Issue by tonysamperi** [ramboxapp/community-edition#2915]
### Steps to reproduce

1. enable "Do not disturb"
2. play an audio message on whatsapp

### Expected behavior

I'd expect to hear the audio

### Actual behavior

I can't hear the audio, unless I disable the "do not disturb" mode

### ENVIRONMENT

> Rambox: v 0.7.7

> OS: Win 10

> Arch: x64

**Comment by fvulich** [comment]
With the current implementation of the do not disturb is not possible.

**Comment by tonysamperi** [comment]
> With the current implementation of the do not disturb is not possible.

Do you know why this was implemented? What was the goal here?
When I use "do not disturb" it's usually to turn notifications off...
And actually the button itself has a _bell icon_ so, maybe I'm missing something here...

![image](https://user-images.githubusercontent.com/5957244/101064877-c31fb880-3594-11eb-8b13-4c194adf17d9.png)

![image](https://user-images.githubusercontent.com/5957244/101064584-70de9780-3594-11eb-86a5-74f14f5604ec.png)

**Comment by fvulich** [comment]
If you want to explore a way to make this possible whilst the notification sound is still muted I suggest you to try something in the 
`/resources/js/rambox-service-api.js` file. Something like override the silent property of the options object of the notification. I couldn't test this but seems to be a good starting point. You also will have to check that other apps that are not the one that you have active don't emit any sound because it will leave the "do not disturb" feature useless

**Comment by tonysamperi** [comment]
What about adding another button which purpose is only to override this setting for all the tabs?
In this way there's no risk of damaging the "do not disturb" feature (now I see why the sounds were also muted).

![image](https://user-images.githubusercontent.com/5957244/101183773-3b977f80-3650-11eb-99e1-d54d5b839bf3.png)

**Comment by fvulich** [comment]
Adding a new option doesn't seem as a good approach.

**Comment by tonysamperi** [comment]
I disagree. This is the situation:

1) You admit the line I found above (`setAudioMuted`) doesn't have to be there => you remove the line and the problem is solved
2) You don't, in which case it means you cannot play audios => you create another button which only deactivates notifications but leaves audio intact
3) you do nothing, the problem stays there, no big deal

anyways if there's another way, it's more likely that someone who knows the code will find it. 

Bests!

**Comment by bkimmett** [comment]
My two cents: I _like_ that DnD turns off audio, and that's what I use it for most of the time (I can already turn off notifications from my system). I wouldn't want that part of the feature to be removed.

**Comment by tonysamperi** [comment]
Yeah, I agree. That's why I proposed to add another button..
Anyway I think I'll get used to only turn notifications off trough this button:

![image](https://user-images.githubusercontent.com/5957244/104624801-4eac5f00-5694-11eb-8d45-6f2196ff64fc.png)

I'm closing the issue, since on windows it's not necessary anymore!

**Comment by dansseg** [comment]
I'm also missing this functionality. It would be great to have the possibility to configure whether audio messages should also be muted or not.

Saying that DnD should turn off audio as well, because you can turn off notifications with Windows functionality, does not make sense. You can also turn off sounds only for Rambox in Windows (via Volume Mixer)...

**Comment by bkimmett** [comment]
macOS user over here. Sadly, macOS has no equivalent to Volume Mixer - Rambox would need a volume toggle in-app if I wanted to mute it.

Fortunately, one already exists in the form of the DnD functionality. If the devs want to split that into a separate toggle, that'd be fine, but I only ask that they not remove audio muting entirely.
