### ISSUE TITLE
Unable to upload files in Telegram

### ISSUE THREAD

**Issue by jEsuSdA** [ramboxapp/community-edition#2917]
Unable to upload files and images in Telegram.

When trying to add any archive in Telegram, the transfer freezes.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> linux x64 5.2.0-20.1-liquorix-amd64

**Comment by fvulich** [comment]
What package are you using? Could you try with a different one? Because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)
