### ISSUE TITLE
Rambox forget all added services after app restart

### ISSUE THREAD

**Issue by tifDev** [ramboxapp/community-edition#2937]
### Steps to reproduce

1. Add service
2. Close rambox
3. Launch rambox

### Expected behavior

Keep the services added.

### Actual behavior
It forgets all added services.

### ENVIRONMENT

Version: 0.7.7
Platform: linux (x64)
Electron: 7.2.4

I don't know why this happening, used to work good since day 1, and today it started to have this issue.

Thank you

**Comment by fvulich** [comment]
That's odd, please check that you don't have more than one installation of Rambox in your Linux. It could happen that you have, for instance, Snap and AppImage at the same time, and they don't share the same user data folder.  

If that doesn't do the trick, could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services)  because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

Since you are a Linux user you could try different packages because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)

**Comment by tifDev** [comment]
Nop, I only have AppImage. I've tried:

1. Clear Cache -> Same behaviour
2. Clear local storage -> Same behaviour
3. Download AppImage again -> Same behaviour
4. Follow the guide **Clean-Uninstall** -> It's now working fine

Thank you for your support and time
