### ISSUE TITLE
Rambox hogging system resources

### ISSUE THREAD

**Issue by bpraj** [ramboxapp/community-edition#2960]
From the day of installing the community edition of Rambox, observing that the app keeps intermittently freezing with the message indicator on the window bar as (not responding) and appears to access high system resources

### Steps to reproduce

1. Within minutes of starting up Rambox, Experiencing intermittently freezes with the message indicator (not responding) on the window bar & the system/PC slows down too much  when switching between app services inside Rambox
2. observed using process lasso app & found rambox affecting system responsiveness 
3. When exit Rambox, system behaves normal

### Expected behavior

1. Rambox should be functioning as a normal without much freezes

### Actual behavior

1. Rambox keeps slowing down the whole system, my observation is it is accessing system resources too much & i suspect it is because i have configured 5 mail services & 2 instant messenger services

### ENVIRONMENT
Rambox Version: 0.7.7
Platform: win32 (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by fvulich** [comment]
It seems that an app inside Rambox CE is crashing, could you try to do this? Once you notice that Rambox CE is consuming an abnormal amount of resources, try to disable apps one by one to see if one of them is the culprit.

If that doesn't do the trick, could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

If you are a Linux user you could try different packages because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)

Related #2104
