### ISSUE TITLE
Google considers the browser insecure

### ISSUE THREAD

**Issue by crdawson** [ramboxapp/community-edition#2962]
I know this had been an issue in the past which was worked around in a previous update, but it seems to be occurring again now. I can't log in to Google Messages through Rambox (using Google Fi in my case; not sure if "regular" Messages for Web works), because Google tells me "This browser or app may not be secure."

I suspect there is a sort of "arms race" going on here and there may be a point at which a workaround is no longer feasible, but I'm hoping that's not the case...

### Steps to reproduce

1. Add "Messages" to Rambox
2. Select "Get Started" under "Have Google Fi"
3. Enter Google credentials

### Expected behavior

Log in to Google Messages

### Actual behavior

Receive an error message from Google, saying "This browser or app may not be secure."

### ENVIRONMENT

> Rambox: v0.7.7

> OS: Ubuntu 18.04 LTS

> Arch: x64

**Comment by fvulich** [comment]
We couldn't reproduce this issue. Can you try deleting the Messages apps and adding it again? If that doesn't do the trick, could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.
