### ISSUE TITLE
Service tabs do not gain focus when switching between them using keyboard controls

### ISSUE THREAD

**Issue by bkimmett** [ramboxapp/community-edition#2963]
### Steps to reproduce

1. Open two chat service tabs in Rambox. (I tested this with Discord but it works with Slack and probably other services)
2. Get to the point where you can send messages in both chat tabs.
3. Switch between the tabs using the keyboard controls (Cmd-1, Cmd-2, etc.) 

### Expected behavior

The switched-to tab will gain focus, as indicated by the insertion point appearing in the message box.

### Actual behavior

The tab switched from keeps focus; if you type, your typing appears in the previous tab (you can see it by switching back).

### ENVIRONMENT

> Rambox: v0.7.7

> OS: macOS 10.12.6

> Arch: x64

**Comment by fvulich** [comment]
We couldn't reproduce this issue. Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

related #2754

**Comment by bkimmett** [comment]
...OK, I tried it just now, before trying to clear the cache/etc, and it's currently working properly. I'm not sure what changed (restarting the app? my computer?), but the fault no longer occurs.

Thanks for the help! 😅 If it recurs I'll try and figure out if there's a way to clear it before opening an issue again.
