### ISSUE TITLE
Images on Telegram

### ISSUE THREAD

**Issue by simotro** [ramboxapp/community-edition#2965]
The images on Telegram are not visible until you click on "reload current service"

	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> linux x64 5.4.0-65-generic

**Comment by fvulich** [comment]
We couldn't reproduce this issue. Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

**Comment by mhatvan** [comment]
This happens to me as well. 
Also a Linux machine like the author, I could check if it happens on my Mac to see if it is OS specific.
