### ISSUE TITLE
Most of the icons are missing on the toolbar

### ISSUE THREAD

**Issue by binyamina** [ramboxapp/community-edition#2966]
Frequent icons are missing (whatsapp, gmail, Telegram, calendar, etc) on the toolbar, although the service works well.
![image](https://user-images.githubusercontent.com/33001300/108060439-8a559280-705f-11eb-87ba-380507ca540e.png)

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.16299

**Comment by fvulich** [comment]
Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

**Comment by binyamina** [comment]
I did all what you suggested:
Clear cache, clear local storage and even clean install (and then install 0.7.7 version again).
The bug still happens.. only google keep icon is displayed

**Comment by binyamina** [comment]
After reboot - only the calendar icon is missing..
![image](https://user-images.githubusercontent.com/33001300/109816362-51a9e180-7c39-11eb-9a2d-d56b9fbcefc5.png)

**Comment by fvulich** [comment]
Seems to be sorted, this could happen in a weak internet connection

**Comment by binyamina** [comment]
But it happens constantly on different computers, and I have fiber internet connection (~500 MB/s)
