### ISSUE TITLE
After triggering several times (really quick) enable/disable DND, the alerts can get stuck in middle screen.

### ISSUE THREAD

**Issue by Agamenox** [ramboxapp/community-edition#2990]
### Steps to reproduce
0. Enable a Bunch of Services
1.  Maximixe Windows
2. Enable Dont Disturb
3. Disable Dont Disturb
4. Enable Dont Disturb  
5.  several times

### Expected behavior

several pop appear in middle of application and dont go away... they remain stuck in middle of screen, cant click whatsapp label.
this is a screen taken 30 minutes later https://i.imgur.com/s0AsdtS.png the alerts remain in place

### ENVIRONMENT

Windows 10 16 Gb RAM HP pro Desk 600 Core i7 2 Screens 29", rambox in secondary screen. 

> Rambox: v0.7.7

> OS: win32 (x64)

Versión: 0.7.7
Plataforma: win32 (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

¡Hey Ramiro sera por tener dos pantallas grandes a la vez?

**Comment by fvulich** [comment]
I couldn't reproduce it, but I see what you mean. We'll check this out.

**Comment by incendor** [comment]
Hi, I can reliably reproduce this, but for me it not only happens when triggering DND quickly on and off, but also when enabling it once and leaving it like that.

Rambox version: 0.7.7
Windows Version: 10 x64 build 19041.804

Active Services:
- WhatsApp
- Slack
- 3x gmail
- Mattermost
- custom service displaying web content from server in LAN

**Comment by Agamenox** [comment]
Still the same problem continues, the alert message keeps getting stuck in the GUI.
![Rambox_6PTfufqgSR](https://user-images.githubusercontent.com/8619960/122465553-d9fc8a00-cf7d-11eb-8acf-ebb67fde2641.png)
