### ISSUE TITLE
Cannot read Slack

### ISSUE THREAD

**Issue by ivanovishado** [ramboxapp/community-edition#2994]
### Steps to reproduce

1. Open Rambox.
2. Go to any Slack tab.

### Expected behavior

Be able to interact normally with Slack tabs.

### Actual behavior

Not being able to load any Slack content.

### ENVIRONMENT

> Rambox: v0.7.7

> OS: macOS Big Sur v11.2.3

> Arch: x64

Here's a screenshot of what I see when opening a Slack tab:
![image](https://user-images.githubusercontent.com/17692634/114098916-a4ee0000-9887-11eb-9f14-46373540cae7.png)

**Comment by fvulich** [comment]
I could reproduce this issue, could you try deleting the Slack app and adding it again? If that doesn't do the trick could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

**Comment by ivanovishado** [comment]
Thanks. I went directly for the Clear cache & storage solution and it worked!
