### ISSUE TITLE
Non of the Services are starting after a mac restart

### ISSUE THREAD

**Issue by christianfroehlichconsulting** [ramboxapp/community-edition#2997]
### Steps to reproduce

1. Have some Services
2. leave the app open when you restart
3. after restarting all services are blank - only a white page. Even after an hour its still blank.

### Expected behavior

to start the services/to display anything

### Actual behavior

not doing nothing

### ENVIRONMENT

Version: 0.7.7
Plattform: darwin (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

2,3 GHz Dual-Core Intel Core i5
8 GB 2133 MHz LPDDR3

**Comment by christianfroehlichconsulting** [comment]
Workaround: disable and enable all services one by one.

**Comment by fvulich** [comment]
It could be that when the app loads the internet connection it isn't available yet. Did you try closing the app and open it again?

If that doesn't do the trick, could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

**Comment by christianfroehlichconsulting** [comment]
Thank you! Its working as expected as soon you log in into rambox.
