### ISSUE TITLE
Restarting computer required re-login on every Service

### ISSUE THREAD

**Issue by takabanana** [ramboxapp/community-edition#3057]
Restarted computer, and every single one of my Services required login.
Doesn't Rambox keep the session/login info for each Service cached?

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19043

**Comment by fvulich** [comment]
That's odd. Can you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

If you are a Linux user you could try different packages because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)
