### ISSUE TITLE
Services not loaded after Rambox crash

### ISSUE THREAD

**Issue by bocekm** [ramboxapp/community-edition#3101]
### Steps to reproduce

1. Install v0.7.9-3 rpm package
2. Set up services
3. Do something that crashes Rambox (in my case it was clicking on `[Message clipped]  View entire message` in GMail)
4. Start the Rambox up and the services are gone

### Expected behavior

Rambox is started with opening all the previously set up services.

### Actual behavior

Rambox is loaded clean in factory settings after having Rambox crash before that. All the settings still exist in ~/.config/Rambox/. I've got 11 service folders under ~/.config/Rambox/Partitions/. Why are they ignored and how to tell Rambox to use them?
Rebooting system or quitting and starting Rambox again does not help.

### ENVIRONMENT

Rambox: v0.7.9-3
OS: Fedora 33
Arch: x64

**Comment by MarcusArthur** [comment]
I just had the same problem and I don't know how to fix it

**Comment by fvulich** [comment]
We couldn't reproduce your issue.

Can you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

Can you try with a different package? Because depending on your Linux distribution, some works better than others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)

**Comment by bocekm** [comment]
Hi @fvulich, I've already reinstalled Rambox from scratch on Fedora 34 (Rambox-0.7.9-linux-x86_64.rpm) and re-added all services manually, so I can't do any debugging anymore. So far it works.

But anyway, I expect that the backup procedure (I was not using it before the issue) would back up only active services (in opened tabs in Rambox) and there were none at that time of my issue.
