### ISSUE TITLE
Constant "UPDATE AVAILABLE Click to Update Whatsapp" warning

### ISSUE THREAD

**Issue by SirLogician** [ramboxapp/community-edition#3138]
Whatsapp and Whatsapp Business keeps displaying "UPDATE AVAILABLE Click to Update Whatsapp" warning. I click on it and do the update but it does not go away. Sometimes it takes 10-20 clicks to get rid of it. But when app starts next day, its again there. I don't know if its a bug or a continuing update on whatsapp end but if latter I suggest this update be automatic. Clicking it tens of times everytime we start the app, makes it difficult to use.

![Rambox_pJRsp4mbuJ](https://user-images.githubusercontent.com/1125706/138052253-aac35bcc-6bba-4e8e-8831-62434d621e90.png)
	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> win32 x64 6.1.7600

**Comment by tobmaster** [comment]
@SirLogician I am not from the rambox team, but it may do the trick for you when you right click the whatsapp tab, select developer tools. Then in the new opened window click the Tab Application, Clear Storage and the Button Clear Site data.
You then close that window and right click the whatsapp tab again and choose Reload. 
Then you need to connect with your phone again but the problem is hopefully away :)

**Comment by fvulich** [comment]
Duplicate #2217 You can try the [workaround](https://github.com/ramboxapp/community-edition/issues/2217#issuecomment-562023784) posted there
