### ISSUE TITLE
Feature suggestion: Global zoom

### ISSUE THREAD

**Issue by charris179** [ramboxapp/community-edition#539]
An option to set a zoom level that would apply to all windows for HiDPI displays

**Comment by guedressel** [comment]
Different zoom levels are necessary on different displays. But also different zoom levels are required between different services. Hence I don't see _one_ global zoom level to be set.
Though the zoom levels one may have set to a certain service on a certain hardware may persist (as suggested in #716 ).

Worth mentioning: such persisted zoom level settings may never be synced between different hosts since it would not resolve the issue described here.

**Comment by saenzramiro** [comment]
I don't think is a good idea to have a global zoom... for me is unuseless.

**Comment by charris179** [comment]
Retained zoom would be even better! I was just sick of zooming into every
page on my high dpi screen every time I restarted rambox.

Chris

**Comment by Oo-Johnny** [comment]
How about an option to disable zoom? I get that problem constantly with a macbook and trackpad

**Comment by larsenwork** [comment]
https://github.com/saenzramiro/rambox/issues/539#issuecomment-336355222 Yes, and/or an option to reset zoom somewhere too.
