### ISSUE TITLE
Telegram needs a reload to show stickers and thumbnails in full size

### ISSUE THREAD

**Issue by notNSANE** [ramboxapp/community-edition#644]
### Steps to reproduce

1.  Open telegram service with a logged in account
2.  Use a sticker or embed an image

### Expected behavior

Stickers and embedded images are correctly shown in proper size

### Actual behavior

Stickers and embedded images are shown very tiny

### ENVIRONMENT

> Rambox: v0.5.3
> OS: Windows 10
> Arch: x64

---

This issue is pretty old. Every time I start Rambox I also do a Reload so I can get the normal sized emoji and thumbnails.

I think it's related to #142.

**Comment by taniadaniela** [comment]
I'm experiencing the same issue, reload the app and stickers still small.. on mac OS sierra with rambox 0.5.3

**Comment by saenzramiro** [comment]
Ok, so if we make Telegram full-width maybe will fix this.

**Comment by edmundlaugasson** [comment]
Telegram needs reload even windowed size to show layout properly. Here tested in Linux.

**Comment by Ziggoto** [comment]
Up. Same here

**Comment by el-seirh** [comment]
Still experiencing this behaviour with all kind of images (gifs, pics and stickers) after updating to rambox-0.5.17-1 on Arch Linux makes me wonder a bit why this issue still exists after 1.5 years.
Images can at least be enlarged by clicking on them, but for gifs and stickers your pretty much lost and cannot receive their message since they're so microscopically small. This is a critical issue in my opinion.
