### ISSUE TITLE
Added Gmail and now i have 23 gmails and they won't go away

### ISSUE THREAD

**Issue by justin-newman** [ramboxapp/community-edition#893]
All I did was add gmail to the list of apps and it added 23 of them and now I can't remove them. They will go away if I hit the remove all button, but then they come back if I try to add any other apps or if I refresh.

I did not click the add button more than once. 

I also tried saving a backup with the empty list of items, but when I try to restore or refresh they still all come back.

Tried rebooting my PC, didn't work.

![image](https://cloud.githubusercontent.com/assets/23383538/26648335/65a9d6be-45ff-11e7-831a-21b7f7f5ab70.png)

	
	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 10.0.15063

**Comment by nmat** [comment]
What happens if you click the little trashcan and remove all of them....then try to add gmail again...can it be reproduced in this manner?

Note I did add gmail after the 0.5.9 upgrade on win 10 also but do not have this problem at all.

Maybe you can also have a screenshot of the settings you are using if there are any specific settings that could cause this....
