### ISSUE TITLE
The Electron default application is accidently opened at session start

### ISSUE THREAD

**Issue by Deuchnord** [ramboxapp/community-edition#919]
### Steps to reproduce

1. Start Rambox

### Expected behavior

Just starts Rambox.

### Actual behavior

Starts Rambox and places an `electron.desktop` file in my `~/.config/autostart` folder, which causes the window reproduced below to show up at session start.

![Electron default app](https://cloud.githubusercontent.com/assets/7600265/26772623/ea4142ac-49c6-11e7-9dc7-6f91e65ab9bc.png)

I tried to remove this desktop file, but it is created again at the next Rambox start.

Content of `~/.config/electron.desktop` is the following:

```desktop
[Desktop Entry]
Type=Application
Version=1.0
Name=electron
Comment=electronstartup script
Exec=/usr/lib/electron/electron --hidden
StartupNotify=false
Terminal=false
```

### ENVIRONMENT

> Rambox: v0.5.9 (installed from [AUR](https://aur.archlinux.org/packages/rambox/))

> OS: Arch Linux

> Arch: x64

**Comment by saenzramiro** [comment]
@flying-sheep Can you help us with this please?

**Comment by flying-sheep** [comment]
what lib do you use to create the autostart file? maybe it’s configured wrong.

**Comment by HenningCash** [comment]
I have the same issue and installed Rambox from Linux AUR. The Rambox package from AUR contains some additional scripts to hook into autostart and [modifies electrons paths](https://aur.archlinux.org/cgit/aur.git/tree/rambox.js?h=rambox). So I would say a) This is nothing that the Rambox team can fix and b) Because an autostart file is already included simply uncheck the option in Rambox settings.
