### ISSUE TITLE
Option to customize zoom or scale of whole window content

### ISSUE THREAD

**Issue by stanis64** [ramboxapp/community-edition#934]

**Comment by xarinatan** [comment]
Does this imply the issue that I'm running into; namely that the Rambox "UI" is zoomed out, and I cannot fix it? Because I'll open a separate issue otherwise.

Also it'd be nice to have some QA done for scaling/zooming anyway because every time I zoom in or out with either my keyboard or mouse the whole thing hangs for 5+ seconds, granted this is an i3 2310M so it's not the fastest CPU in the world, but it's still a little strange imho.

**Comment by saenzramiro** [comment]
Do you mean about zooming Rambox instead of each service?

**Comment by stanis64** [comment]
Yes, that would be great

**Comment by gingerbeardman** [comment]
I also have this issue and it was closed without resolution https://github.com/saenzramiro/rambox/issues/930

**Comment by gingerbeardman** [comment]
Stale but still an issue
